
import { TcmDatabase, Syndrome } from './types';
import { MACIOCIA_100_PATTERNS } from './maciocia_100_patterns';

// Helper to parse strings into arrays for the DB
const toArray = (str: string) => str.split(/[,;]\s?/).map(s => s.trim()).filter(s => s);
const parsePoints = (str: string) => toArray(str).map(s => {
    // Normalize codes
    return s.split(' ')[0].replace('HE-', 'HT').replace('LIV-', 'LR').replace('Ren-', 'CV').replace('Du-', 'GV').replace('P-', 'PC').replace('-', '');
});

export const MACIOCIA_SYNDROMES: Syndrome[] = [
  // --- FIRE (HEART / SI) ---
  {
    id: "HEART_QI_DEFICIENCY",
    name_id: "Defisiensi Qi Jantung",
    name_en: "Heart Qi Deficiency",
    primary_organs: ["Heart"],
    wuxing_element: "Fire",
    pattern_type: "deficiency",
    clinical_manifestations: toArray("Palpitations, Shortness of breath on exertion, Pale face, Spontaneous sweating, Tiredness, Slight depression"),
    tongue: toArray("Pale, Normal or slightly swollen"),
    pulse: toArray("Empty (Weak)"),
    key_symptoms: toArray("Palpitations, Shortness of breath, Empty pulse"),
    treatment_principle: toArray("Tonify Heart-Qi"),
    acupuncture_points: parsePoints("HT-5, PC-6, CV-14, BL-15, CV-17"),
  },
  {
    id: "PHLEGM_FIRE_HARASSING_HEART",
    name_id: "Dahak-Api Mengganggu Jantung",
    name_en: "Phlegm-Fire Harassing the Heart",
    primary_organs: ["Heart"],
    wuxing_element: "Fire",
    pattern_type: "excess_damp_heat",
    clinical_manifestations: toArray("Palpitations, Thirst, Red face, Bitter taste, A feeling of oppression of the chest, Expectoration of phlegm, Rattling sound in the throat, Mental restlessness, Insomnia, Dream-disturbed sleep, Agitation, Incoherent speech, Mental confusion, Rash behavior, Tendency to hit or scold people, Uncontrolled laughter or crying, Shouting, Muttering to oneself, Mental depression and dullness, Manic behavior"),
    tongue: toArray("Red, Swollen, Yellow dry sticky coating, Deep Heart crack"),
    pulse: toArray("Full-Rapid-Slippery or Rapid-Overflowing-Slippery"),
    key_symptoms: toArray("Mental symptoms, Red-Swollen tongue with yellow sticky coating, Slippery-Rapid pulse"),
    treatment_principle: toArray("Clear the Heart, Drain Fire, Resolve Phlegm, Calm the Mind, Open the Mind's orifices"),
    acupuncture_points: parsePoints("PC-5, HT-8, HT-9, CV-15, BL-15, ST-40, GV-20, GV-24, GB-13, GB-15, DU-26"),
  },
  {
    id: "FULL_HEAT_IN_SMALL_INTESTINE",
    name_id: "Panas Penuh di Usus Kecil",
    name_en: "Full Heat in Small Intestine",
    primary_organs: ["Small Intestine"],
    wuxing_element: "Fire",
    pattern_type: "full_heat_excess",
    clinical_manifestations: toArray("Mental restlessness, Insomnia, Tongue ulcers, Pain in the throat, Deafness, Uncomfortable feeling and heat sensation in the chest, Abdominal pain, Thirst with a desire to drink cold liquids, Scanty and dark urine, Burning pain on urination, Blood in urine"),
    tongue: toArray("Red with redder and swollen tip, Yellow coating"),
    pulse: toArray("Rapid-Overflowing, especially in the Front position, or Rapid-Wiry"),
    key_symptoms: toArray("Tongue ulcers, Scanty dark urine, Burning pain on urination"),
    treatment_principle: toArray("Drain Fire from the Heart and Small Intestine"),
    acupuncture_points: parsePoints("SI-2, SI-5, HT-5, HT-8, ST-39"),
  },
  {
    id: "heart-fire-blazing",
    name_id: "Api Jantung Berkobar",
    name_en: "Heart Fire-Blazing",
    name_pinyin: "Xin Huo Shang Yan",
    primary_organs: ["Heart"],
    wuxing_element: "Fire",
    pattern_type: "Excess Heat",
    clinical_manifestations: ["Palpitations", "Thirst", "Mouth and tongue ulcers", "Mental restlessness", "Feeling of heat, red face", "Insomnia", "Dark urine or blood in urine", "Bitter taste"],
    tongue: ["Red tongue, tip redder and swollen with red points, yellow coating, possible midline crack"],
    pulse: ["Full-Rapid-Overflowing (left Front position), may be Hasty"],
    key_symptoms: ["Tongue ulcers", "Thirst", "Palpitations", "Red tongue"],
    treatment_principle: ["Clear the Heart, drain Fire, and calm the Mind (Shen)"],
    acupuncture_points: parsePoints("HT-9, HT-7, SP-6, LI-11, GV-24, DU-19, HT-8, CV-15, KI-6"),
    herbal_prescription: "Xie Xin Tang (Draining the Heart Decoction)",
    needling_method: "Reducing on all points except SP-6 and KI-6 (reinforcing); no moxa",
    diagnostic_tip: "Tongue ulcers + red tongue tip + palpitations = classic Heart Fire"
  },
  {
    id: "HEART_BLOOD_DEFICIENCY",
    name_id: "Defisiensi Darah Jantung",
    name_en: "Heart Blood Deficiency",
    primary_organs: ["Heart"],
    wuxing_element: "Fire",
    pattern_type: "deficiency",
    clinical_manifestations: toArray("Palpitations, Insomnia, Dream-disturbed sleep, Poor memory, Dizziness, Anxiety, Dull-pale complexion, Pale lips"),
    tongue: toArray("Pale, Thin, Slightly dry"),
    pulse: toArray("Choppy or Fine (Weak)"),
    key_symptoms: toArray("Palpitations, Insomnia, Pale tongue"),
    treatment_principle: toArray("Tonify Heart-Blood, Calm the Mind"),
    acupuncture_points: parsePoints("HT-7, PC-6, CV-14, CV-15, BL-15, BL-20, BL-17, ST-36"),
  },
  {
    id: "HEART_YIN_DEFICIENCY",
    name_id: "Defisiensi Yin Jantung",
    name_en: "Heart Yin Deficiency",
    primary_organs: ["Heart"],
    wuxing_element: "Fire",
    pattern_type: "deficiency_heat",
    clinical_manifestations: toArray("Palpitations, Insomnia, Dream-disturbed sleep, Poor memory, Anxiety, Mental restlessness, 'Five-palm heat', Night sweating, Dry mouth and throat"),
    tongue: toArray("Red, No coating, Tip redder and swollen with red points, Midline crack to tip"),
    pulse: toArray("Floating-Empty, Rapid"),
    key_symptoms: toArray("Palpitations, Mental restlessness, Night sweating, Red-Peeled tongue"),
    treatment_principle: toArray("Nourish Heart-Yin, Calm the Mind, Clear Empty-Heat"),
    acupuncture_points: parsePoints("HT-7, PC-6, CV-14, CV-15, HT-6, SP-6, KI-7"),
  },
  {
    id: "heart-yang-deficiency",
    name_id: "Defisiensi Yang Jantung",
    name_en: "Heart-Yang Deficiency",
    primary_organs: ["Heart"],
    wuxing_element: "Fire",
    pattern_type: "Cold Deficiency",
    clinical_manifestations: ["Palpitations", "Shortness of breath on exertion", "Tiredness, spontaneous sweating", "Feeling cold, cold hands"],
    tongue: ["Pale, slightly wet"],
    pulse: ["Deep-Weak (may be Knotted)"],
    key_symptoms: ["Palpitations + cold hands + spontaneous sweating"],
    treatment_principle: ["Tonify and warm Heart-Yang, support Heart-Qi"],
    acupuncture_points: parsePoints("HT-5, PC-6, BL-15, CV-17, CV-6"),
    herbal_prescription: "Rou Fu Bao Yuan Tang"
  },
  {
    id: "HEART_BLOOD_STASIS",
    name_id: "Statis Darah Jantung",
    name_en: "Heart Blood Stasis",
    primary_organs: ["Heart"],
    wuxing_element: "Fire",
    pattern_type: "stagnation",
    clinical_manifestations: toArray("Palpitations, Stabbing or pricking pain in the chest which may radiate to the inner aspect of the left arm or to the shoulder, A feeling of oppression or constriction of the chest, Cyanosis of lips and nails, Cold hands"),
    tongue: toArray("Purple in its entirety or only on the sides in the chest area"),
    pulse: toArray("Choppy, Wiry or Knotted"),
    key_symptoms: toArray("Stabbing pain in the chest, Purple lips, Purple tongue"),
    treatment_principle: toArray("Move Blood, Eliminate stasis, Tonify and warm Heart-Yang, Calm the Mind"),
    acupuncture_points: parsePoints("PC-6, PC-4, HT-7, CV-14, BL-15, BL-17, SP-10, CV-17"),
  },

  // --- WOOD (LIVER / GB) ---
  {
    id: "LIVER_WIND_AGITATING_WITHIN",
    name_id: "Angin Hati Bergerak di Dalam",
    name_en: "Liver Wind Agitating Within",
    primary_organs: ["Liver"],
    wuxing_element: "Wood",
    pattern_type: "excess_heat",
    clinical_manifestations: toArray("Tremors, Tics, Numbness, Dizziness, Vertigo, Headache, Convulsions, Paralysis, Hemiplegia, Deviation of eye and mouth, Aphasia or difficult speech"),
    tongue: toArray("Deviated, Stiff, Red or Pale depending on underlying condition"),
    pulse: toArray("Wiry"),
    key_symptoms: toArray("Tremors, Tics, Severe dizziness, Deviated tongue"),
    treatment_principle: toArray("Subdue Liver-Wind, Pacify the Liver"),
    acupuncture_points: parsePoints("LR-3, GB-20, DU-16, DU-20, GB-34, LI-4"),
  },
  {
    id: "DAMP_HEAT_IN_LIVER_AND_GB",
    name_id: "Lembap-Panas di Hati dan Empedu",
    name_en: "Damp-Heat in Liver and Gallbladder",
    primary_organs: ["Liver", "Gall Bladder"],
    wuxing_element: "Wood",
    pattern_type: "excess_damp_heat",
    clinical_manifestations: toArray("Hypochondriac pain, Fullness and distension, Nausea, Vomiting, Inability to digest fats, Yellow complexion and eyes (jaundice), Bitter taste, Sticky taste, No appetite, Scanty dark yellow urine, Fever, Thirst without desire to drink, Vaginal discharge, Itching, Swelling and pain of scrotum"),
    tongue: toArray("Red body, Thick sticky yellow coating (especially on the sides)"),
    pulse: toArray("Slippery-Wiry-Rapid"),
    key_symptoms: toArray("Hypochondriac pain, Bitter taste, Thick sticky yellow coating on the right side"),
    treatment_principle: toArray("Resolve Dampness, Clear Heat from Liver and Gall Bladder"),
    acupuncture_points: parsePoints("GB-24, LR-14, GB-34, LI-11, TB-6, LR-2, SP-9, CV-12"),
  },
  {
    id: "liver-fire-blazing",
    name_id: "Api Liver Berkobar",
    name_en: "Liver Fire-Blazing",
    name_pinyin: "Gan Huo Shang Yan",
    primary_organs: ["Liver"],
    wuxing_element: "Wood",
    pattern_type: "Excess Heat",
    clinical_manifestations: ["Headache, dizziness", "Red face and eyes", "Irritability, outbursts of anger", "Bitter taste, dry throat", "Constipation", "Dark-yellow urine", "Tinnitus"],
    tongue: ["Red tongue with redder sides and yellow coating"],
    pulse: ["Wiry and Rapid"],
    key_symptoms: ["Red eyes/face", "Anger, irritability", "Bitter taste", "Wiry-rapid pulse"],
    treatment_principle: ["Clear Liver-Fire, drain Heat, and subdue rising"],
    acupuncture_points: parsePoints("LR-2, LR-3, GB-20, LI-11, GV-24, Taiyang"),
    herbal_prescription: "Long Dan Xie Gan Tang",
    needling_method: "Reducing on all points; no moxa"
  },
  {
    id: "LIVER_QI_STAGNATION",
    name_id: "Stagnasi Qi Hati",
    name_en: "Liver Qi Stagnation",
    primary_organs: ["Liver"],
    wuxing_element: "Wood",
    pattern_type: "stagnation",
    clinical_manifestations: toArray("Distension of hypochondrium/chest, Sighing, Hiccups, Nausea, Vomiting, Epigastric pain, Poor appetite, Sour regurgitation, Feeling of a lump in the throat, Irritability, Depression, Irregular periods, PMS"),
    tongue: toArray("Normal or slightly red on the sides"),
    pulse: toArray("Wiry (especially on the left)"),
    key_symptoms: toArray("Hypochondriac distension, Sighing, Irritability, Wiry pulse"),
    treatment_principle: toArray("Smooth the Liver, Move Qi, Harmonize the Spirit"),
    acupuncture_points: parsePoints("LR-3, GB-34, LR-14, PC-6, TB-6, CV-12"),
  },
  {
    id: "LIVER_BLOOD_DEFICIENCY",
    name_id: "Defisiensi Darah Hati",
    name_en: "Liver Blood Deficiency",
    primary_organs: ["Liver"],
    wuxing_element: "Wood",
    pattern_type: "deficiency",
    clinical_manifestations: toArray("Dizziness, Numbness or tingling of limbs, Insomnia, Blurred vision, 'Floaters' in eyes, Diminished night vision, Scanty menstruation or amenorrhoea, Dull-pale complexion, Pale lips, Muscular weakness, Muscle spasms, Cramps, Brittle nails, Dry hair and skin"),
    tongue: toArray("Pale, especially on the sides, which in extreme cases can assume an orange colour, Thin and slightly dry"),
    pulse: toArray("Choppy or Fine"),
    key_symptoms: toArray("Blurred vision, Scanty periods, Pale tongue"),
    treatment_principle: toArray("Tonify Liver-Blood"),
    acupuncture_points: parsePoints("LR-8, ST-36, SP-6, CV-4, BL-18, BL-20, BL-23, BL-17"),
  },
  {
    id: "LIVER_YANG_RISING",
    name_id: "Yang Hati Naik",
    name_en: "Liver Yang Rising",
    primary_organs: ["Liver"],
    wuxing_element: "Wood",
    pattern_type: "mixed_deficiency_excess",
    clinical_manifestations: toArray("Headache that may be on the temples, eyes or lateral side of the head, Dizziness, Tinnitus, Deafness, Blurred vision, Dry mouth and throat, Insomnia, Irritability, Feeling worked-up, Shouting in anger"),
    tongue: toArray("Pale (if Liver-Blood deficiency) or Red (if Liver-Yin deficiency)"),
    pulse: toArray("Wiry (if Liver-Blood deficiency) or Wiry-Fine-Rapid (if Liver-Yin deficiency)"),
    key_symptoms: toArray("Headache, Irritability, Wiry pulse"),
    treatment_principle: toArray("Subdue Liver-Yang, Nourish Liver-Yin or Liver-Blood"),
    acupuncture_points: parsePoints("LR-3, GB-20, Taiyang, GB-43, GB-38, BL-2, LR-8, SP-6, KI-3"),
  },

  // --- EARTH (SPLEEN / STOMACH) ---
  {
    id: "DAMP_COLD_INVADING_SPLEEN",
    name_id: "Lembap-Dingin Menyerang Limpa",
    name_en: "Damp-Cold Invading the Spleen",
    primary_organs: ["Spleen"],
    wuxing_element: "Earth",
    pattern_type: "excess_cold",
    clinical_manifestations: toArray("Poor appetite, Feeling of fullness of the epigastrium and/or abdomen, A feeling of cold in the epigastrium which improves with the application of heat, A feeling of heaviness of the head and body, Sweetish taste or absence of taste, No thirst, Loose stools, Lassitude, Tiredness, Nausea, Edema, Dull-white complexion, Excessive white vaginal discharge"),
    tongue: toArray("Pale, Thick sticky white coating"),
    pulse: toArray("Slippery-Slow"),
    key_symptoms: toArray("Fullness in epigastrium, Feeling of heaviness, Thick sticky white coating"),
    treatment_principle: toArray("Resolve Dampness, Expel Cold, Tonify Spleen-Qi"),
    acupuncture_points: parsePoints("SP-9, SP-6, SP-3, CV-12, ST-8, BL-20"),
  },
  {
    id: "DAMP_HEAT_INVADING_SPLEEN",
    name_id: "Lembap-Panas Menyerang Limpa",
    name_en: "Damp-Heat Invading the Spleen",
    primary_organs: ["Spleen"],
    wuxing_element: "Earth",
    pattern_type: "excess_damp_heat",
    clinical_manifestations: toArray("Feeling of fullness of the epigastrium and/or lower abdomen, Epigastric and/or abdominal pain, Poor appetite, Feeling of heaviness, Thirst without desire to drink, Nausea, Vomiting, Loose stools with offensive odor, Burning sensation in the anus, Scanty and dark urine, Low-grade fever, Dull headache with feeling of heaviness, Bitter taste, Itchy skin eruptions, Sweating which does not relieve fever"),
    tongue: toArray("Red, Thick sticky yellow coating"),
    pulse: toArray("Slippery-Rapid"),
    key_symptoms: toArray("Fullness in epigastrium, Feeling of heaviness, Thick sticky yellow coating"),
    treatment_principle: toArray("Resolve Dampness, Clear Heat"),
    acupuncture_points: parsePoints("SP-9, SP-6, LI-11, CV-12, ST-8, BL-20, ST-40"),
  },
  {
    id: "STOMACH_QI_DEFICIENCY",
    name_id: "Defisiensi Qi Lambung",
    name_en: "Stomach Qi Deficiency",
    primary_organs: ["Stomach"],
    wuxing_element: "Earth",
    pattern_type: "deficiency",
    clinical_manifestations: toArray("Uncomfortable feeling in the epigastrium, Lack of appetite, Lack of taste, Loose stools, Tiredness especially in the morning, Weak limbs"),
    tongue: toArray("Pale"),
    pulse: toArray("Empty, especially on the Right Middle position"),
    key_symptoms: toArray("Uncomfortable feeling in epigastrium, Tiredness in the morning, Empty pulse"),
    treatment_principle: toArray("Tonify Stomach-Qi"),
    acupuncture_points: parsePoints("ST-36, CV-12, BL-21, CV-6"),
  },
  {
    id: "FOOD_RETENTION_IN_STOMACH",
    name_id: "Retensi Makanan di Lambung",
    name_en: "Food Retention in the Stomach",
    primary_organs: ["Stomach"],
    wuxing_element: "Earth",
    pattern_type: "stagnation",
    clinical_manifestations: toArray("Fullness, pain and distension of the epigastrium which are relieved by vomiting, Nausea, Vomiting of sour fluids, Foul breath, Sour regurgitation, Belching, Insomnia, Loose stools or constipation, Poor appetite"),
    tongue: toArray("Thick coating (could be white or yellow)"),
    pulse: toArray("Full-Slippery"),
    key_symptoms: toArray("Epigastric fullness relieved by vomiting, Sour regurgitation, Thick coating"),
    treatment_principle: toArray("Resolve Food retention, Stimulate the descending of Stomach-Qi"),
    acupuncture_points: parsePoints("CV-10, CV-12, ST-21, ST-36, ST-44, SP-4, PC-6"),
  },
  {
    id: "SPLEEN_QI_DEFICIENCY",
    name_id: "Defisiensi Qi Limpa",
    name_en: "Spleen Qi Deficiency",
    primary_organs: ["Spleen"],
    wuxing_element: "Earth",
    pattern_type: "deficiency",
    clinical_manifestations: toArray("Poor appetite, Slight abdominal distension after eating, Tiredness, Lassitude, Desire to lie down, Weakness of the limbs, Loose stools, Pale-dull complexion"),
    tongue: toArray("Pale, Teeth marks"),
    pulse: toArray("Empty or Weak"),
    key_symptoms: toArray("Loose stools, Tiredness, Pale tongue with teeth marks"),
    treatment_principle: toArray("Tonify Spleen-Qi, Resolve Dampness"),
    acupuncture_points: parsePoints("CV-12, ST-36, SP-3, SP-6, BL-20, BL-21"),
  },
  {
    id: "SPLEEN_YANG_DEFICIENCY",
    name_id: "Defisiensi Yang Limpa",
    name_en: "Spleen Yang Deficiency",
    primary_organs: ["Spleen"],
    wuxing_element: "Earth",
    pattern_type: "deficiency_cold",
    clinical_manifestations: toArray("Poor appetite, Abdominal distension after eating, Tiredness, Lassitude, Cold feeling, Cold limbs, Edema, Loose stools/Diarrhea"),
    tongue: toArray("Pale, Swollen, Wet"),
    pulse: toArray("Deep, Weak, Slow"),
    key_symptoms: toArray("Loose stools, Cold limbs, Pale-Swollen tongue"),
    treatment_principle: toArray("Warm and Tonify Spleen-Yang, Resolve Dampness"),
    acupuncture_points: parsePoints("CV-12, ST-36, SP-3, SP-6, BL-20, BL-21, GV-4, CV-9"),
    needling_method: "Moxa is essential."
  },
  {
    id: "SPLEEN_QI_SINKING",
    name_id: "Qi Limpa Tenggelam",
    name_en: "Spleen Qi Sinking",
    primary_organs: ["Spleen"],
    wuxing_element: "Earth",
    pattern_type: "deficiency",
    clinical_manifestations: toArray("Poor appetite, Slight abdominal distension after eating, Tiredness, Lassitude, Pale complexion, Weakness of limbs, Loose stools, Depression, Bearing-down sensation in abdomen, Prolapse of stomach, uterus, anus or vagina, Frequency and urgency of urination"),
    tongue: toArray("Pale"),
    pulse: toArray("Empty, Weak"),
    key_symptoms: toArray("Bearing-down sensation, Prolapse of organs, Pale tongue"),
    treatment_principle: toArray("Tonify Spleen-Qi, Raise Qi"),
    acupuncture_points: parsePoints("CV-12, ST-36, SP-3, SP-6, BL-20, BL-21, DU-20, CV-6"),
  },
  {
    id: "STOMACH_YIN_DEFICIENCY",
    name_id: "Defisiensi Yin Lambung",
    name_en: "Stomach Yin Deficiency",
    primary_organs: ["Stomach"],
    wuxing_element: "Earth",
    pattern_type: "deficiency_heat",
    clinical_manifestations: toArray("No appetite or slight hunger with no desire to eat, Constipation (dry stools), Dull or slightly burning epigastric pain, Dry mouth and throat especially in the afternoon, Slight feeling of fullness after eating"),
    tongue: toArray("Peeled in the centre, or without coating, Red in the centre"),
    pulse: toArray("Floating-Empty on the Right Middle position"),
    key_symptoms: toArray("No appetite, Dry mouth, Peeled tongue in the centre"),
    treatment_principle: toArray("Nourish Stomach-Yin, Nourish Fluids"),
    acupuncture_points: parsePoints("ST-36, CV-12, SP-6, KI-3, SP-3"),
  },
  {
    id: "STOMACH_FIRE",
    name_id: "Api Lambung",
    name_en: "Stomach Fire",
    primary_organs: ["Stomach"],
    wuxing_element: "Earth",
    pattern_type: "full_heat_excess",
    clinical_manifestations: toArray("Burning epigastric pain, Intense thirst with desire to drink cold liquids, Mental restlessness, Bleeding gums, Dry stools, Dry mouth, Mouth ulcers, Sour regurgitation, Nausea, Vomiting soon after eating, Excessive hunger, Foul breath, Feeling of heat"),
    tongue: toArray("Red, Thick yellow dry coating"),
    pulse: toArray("Full-Deep-Rapid"),
    key_symptoms: toArray("Burning epigastric pain, Thirst, Thick yellow dry coating"),
    treatment_principle: toArray("Clear Stomach-Fire, Stimulate the descending of Stomach-Qi"),
    acupuncture_points: parsePoints("ST-44, ST-34, ST-21, CV-12, CV-13, LI-11, ST-45"),
  },

  // --- METAL (LUNG / LI) ---
  {
    id: "cold-phlegm-lungs",
    name_id: "Dahak-Dingin di Paru",
    name_en: "Cold-Phlegm in the Lungs",
    primary_organs: ["Lungs"],
    wuxing_element: "Metal",
    pattern_type: "Cold Excess (Interior)",
    clinical_manifestations: ["Cough with copious white watery sputum", "Cough worse with cold", "Feeling cold, cold hands", "Phlegm in throat", "Oppression in chest"],
    tongue: ["Swollen and wet with sticky white coating"],
    pulse: ["Slippery-Slow"],
    key_symptoms: ["Copious white watery sputum", "Feeling cold"],
    treatment_principle: ["Resolve Dampness and Phlegm, restore descending of Lung-Qi"],
    acupuncture_points: parsePoints("LU-5, LU-7, ST-40, CV-17"),
    herbal_prescription: "Er Chen Tang"
  },
  {
    id: "DAMP_HEAT_IN_LARGE_INTESTINE",
    name_id: "Lembap-Panas di Usus Besar",
    name_en: "Damp-Heat in Large Intestine",
    primary_organs: ["Large Intestine"],
    wuxing_element: "Metal",
    pattern_type: "excess_damp_heat",
    clinical_manifestations: toArray("Abdominal pain which is not relieved by a bowel movement, Diarrhea, Mucus and blood in stools, Offensive odor of stools, Burning in the anus, Scanty dark urine, Fever, Sweating which does not decrease the fever, A feeling of heat, Thirst without desire to drink, Feeling of heaviness of the body and limbs"),
    tongue: toArray("Red, Sticky yellow coating"),
    pulse: toArray("Slippery-Rapid"),
    key_symptoms: toArray("Abdominal pain, Diarrhea with mucus and blood, Sticky yellow coating"),
    treatment_principle: toArray("Clear Heat, Resolve Dampness, Stop Diarrhea"),
    acupuncture_points: parsePoints("ST-25, ST-37, LI-11, SP-9, CV-3, BL-25"),
  },
  {
    id: "LARGE_INTESTINE_DRYNESS",
    name_id: "Kekeringan Usus Besar",
    name_en: "Large Intestine Dryness",
    primary_organs: ["Large Intestine"],
    wuxing_element: "Metal",
    pattern_type: "deficiency",
    clinical_manifestations: toArray("Dry stools which are difficult to discharge, Dry mouth and throat, Thin body, Foul breath, Dizziness"),
    tongue: toArray("Dry, either Pale or Red with no rootless coating"),
    pulse: toArray("Fine"),
    key_symptoms: toArray("Dry stools, Dry tongue, Fine pulse"),
    treatment_principle: toArray("Moisten the Intestines, Promote bowel movements"),
    acupuncture_points: parsePoints("ST-25, ST-36, SP-6, KI-6, CV-4"),
  },
  {
    id: "LUNG_QI_DEFICIENCY",
    name_id: "Defisiensi Qi Paru",
    name_en: "Lung Qi Deficiency",
    primary_organs: ["Lung"],
    wuxing_element: "Metal",
    pattern_type: "deficiency",
    clinical_manifestations: toArray("Shortness of breath, Weak voice, Bright-pale complexion, Propensity to catch colds, Tiredness, Spontaneous sweating"),
    tongue: toArray("Pale"),
    pulse: toArray("Empty, especially in the Right Front position"),
    key_symptoms: toArray("Shortness of breath, Weak voice, Propensity to catch colds"),
    treatment_principle: toArray("Tonify Lung-Qi, Warm the Yang"),
    acupuncture_points: parsePoints("LU-9, LU-7, CV-6, BL-13, DU-12, ST-36"),
  },
  {
    id: "LUNG_YIN_DEFICIENCY",
    name_id: "Defisiensi Yin Paru",
    name_en: "Lung Yin Deficiency",
    primary_organs: ["Lung"],
    wuxing_element: "Metal",
    pattern_type: "deficiency_heat",
    clinical_manifestations: toArray("Dry cough, Dry throat, Hoarse voice, Night sweating, Five-palm heat, Low-grade fever in the afternoon, Thin body"),
    tongue: toArray("Red body, No coating, Cracks in the front part"),
    pulse: toArray("Floating-Empty, Rapid"),
    key_symptoms: toArray("Dry cough, Hoarse voice, Night sweating, Red-Peeled tongue"),
    treatment_principle: toArray("Tonify Lung-Yin, Clear Heat, Nourish Body Fluids"),
    acupuncture_points: parsePoints("LU-9, LU-1, BL-13, CV-17, KI-6, SP-6"),
  },
  {
    id: "invasion-lungs-wind-cold",
    name_id: "Invasi Angin-Dingin ke Paru",
    name_en: "Invasion of the Lungs by Wind-Cold",
    primary_organs: ["Lungs"],
    wuxing_element: "Metal",
    pattern_type: "Cold Excess (Exterior)",
    clinical_manifestations: ["Aversion to cold, mild fever", "No sweating", "Body aches, stiff neck", "Cough with thin white sputum", "Runny/blocked nose"],
    tongue: ["Thin white coating"],
    pulse: ["Floating-Tight"],
    key_symptoms: ["No sweating", "Aversion to cold", "Thin white sputum"],
    treatment_principle: ["Release Exterior, expel Wind-Cold, restore Lung diffusion"],
    acupuncture_points: parsePoints("LU-7, LI-4, BL-12, GB-20"),
    herbal_prescription: "Ma Huang Tang"
  },
  {
    id: "WIND_HEAT_INVADING_LUNGS",
    name_id: "Angin-Panas Menyerang Paru",
    name_en: "Wind-Heat Invading the Lungs",
    primary_organs: ["Lung"],
    wuxing_element: "Metal",
    pattern_type: "full_heat_excess",
    clinical_manifestations: toArray("Aversion to cold, Fever, Cough, Sore throat, Stuffed or runny nose with yellow discharge, Headache, Body aches, Slight sweating, Thirst, Swollen tonsils"),
    tongue: toArray("Red on the sides or in the front part, Thin white or yellow coating"),
    pulse: toArray("Floating-Rapid"),
    key_symptoms: toArray("Fever, Sore throat, Floating-Rapid pulse"),
    treatment_principle: toArray("Release the Exterior, Clear Heat, Stimulate the descending and diffusing of Lung-Qi"),
    acupuncture_points: parsePoints("LU-11, LU-10, LI-4, LI-11, DU-14, BL-12, GB-20"),
  },
  {
    id: "PHLEGM_HEAT_IN_LUNGS",
    name_id: "Dahak-Panas di Paru",
    name_en: "Phlegm-Heat in the Lungs",
    primary_organs: ["Lung"],
    wuxing_element: "Metal",
    pattern_type: "excess_damp_heat",
    clinical_manifestations: toArray("Barking cough with profuse sticky yellow or green sputum, Shortness of breath, Wheezing, A feeling of oppression of the chest, Phlegm in the throat, Feeling of heat, Thirst, Insomnia, Agitation, A feeling of heaviness and fuzziness of the head, Dizziness"),
    tongue: toArray("Red, Swollen, Thick sticky yellow coating"),
    pulse: toArray("Slippery-Rapid"),
    key_symptoms: toArray("Cough with yellow sputum, Thick sticky yellow coating, Slippery-Rapid pulse"),
    treatment_principle: toArray("Resolve Phlegm, Clear Heat, Stimulate the descending of Lung-Qi"),
    acupuncture_points: parsePoints("LU-5, LU-7, LU-10, LI-11, LU-1, CV-17, ST-40"),
  },

  // --- WATER (KIDNEY / BLADDER) ---
  {
    id: "KIDNEYS_FAILING_TO_RECEIVE_QI",
    name_id: "Ginjal Gagal Menerima Qi",
    name_en: "Kidneys Failing to Receive Qi",
    primary_organs: ["Kidney", "Lung"],
    wuxing_element: "Water",
    pattern_type: "deficiency",
    clinical_manifestations: toArray("Shortness of breath on exertion, Rapid and weak breathing, Difficulty in inhaling, Chronic cough, Asthma, Spontaneous sweating, Cold limbs, Cold feeling after sweating, Swelling of the face, Thin body, Mental exhaustion, Clear urination during asthma attack, Lower backache, Dizziness, Tinnitus"),
    tongue: toArray("Pale"),
    pulse: toArray("Deep-Weak-Tight"),
    key_symptoms: toArray("Shortness of breath on exertion, Difficulty in inhaling, Deep-Weak pulse"),
    treatment_principle: toArray("Tonify and warm the Kidneys, Stimulate the Kidneys' receiving of Qi, Stimulate the descending of Lung-Qi"),
    acupuncture_points: parsePoints("KI-7, KI-3, LU-7, KI-6, ST-36, BL-23, DU-4, CV-6, CV-17, CV-4"),
  },
  {
    id: "KIDNEY_YANG_DEFICIENCY",
    name_id: "Defisiensi Yang Ginjal",
    name_en: "Kidney Yang Deficiency",
    primary_organs: ["Kidney"],
    wuxing_element: "Water",
    pattern_type: "deficiency_cold",
    clinical_manifestations: toArray("Soreness of back and knees, Cold feeling, Aversion to cold, Weakness of legs, Impotence, Premature ejaculation, Low sperm count, Copious clear urine, Incontinence, Diarrhea at dawn, Edema of legs"),
    tongue: toArray("Pale, Wet, Swollen"),
    pulse: toArray("Deep, Weak, Slow"),
    key_symptoms: toArray("Sore back, Cold limbs, Diarrhea at dawn, Pale-Wet tongue"),
    treatment_principle: toArray("Warm and Tonify Kidney-Yang, Strengthen the Gate of Life"),
    acupuncture_points: parsePoints("KI-3, KI-7, BL-23, DU-4, CV-4, CV-6, BL-52"),
    needling_method: "Reinforcing; Moxa is essential."
  },
  {
    id: "KIDNEY_YIN_DEFICIENCY",
    name_id: "Defisiensi Yin Ginjal",
    name_en: "Kidney Yin Deficiency",
    primary_organs: ["Kidney"],
    wuxing_element: "Water",
    pattern_type: "deficiency_heat",
    clinical_manifestations: toArray("Dizziness, Tinnitus, Vertigo, Poor memory, Night sweating, Dry mouth and throat at night, Low-grade fever, Five-palm heat, Soreness of back and knees, Constipation, Dark-scanty urine"),
    tongue: toArray("Red body, No coating, Cracks"),
    pulse: toArray("Floating-Empty, Rapid"),
    key_symptoms: toArray("Night sweating, Sore back, Red-Peeled tongue"),
    treatment_principle: toArray("Tonify Kidney-Yin, Clear Empty Heat"),
    acupuncture_points: parsePoints("KI-3, KI-6, KI-10, SP-6, CV-4, LU-7"),
  },
  {
    id: "KIDNEY_ESSENCE_DEFICIENCY",
    name_id: "Defisiensi Jing (Esensi) Ginjal",
    name_en: "Kidney Essence Deficiency",
    primary_organs: ["Kidney"],
    wuxing_element: "Water",
    pattern_type: "deficiency",
    clinical_manifestations: toArray("Children: poor bone development, late closure of fontanelle, mental dullness or retardation. Adults: softening of bones, weakness of knees and legs, poor memory, loose teeth, falling hair or premature greying of hair, weakness of sexual activity, lower backache, infertility, sterility, primary amenorrhoea, dizziness, tinnitus, deafness, blurred vision, absent-mindedness, decreased mental sharpness"),
    tongue: toArray("Red and peeled (if Yin deficiency) or Pale (if Yang deficiency)"),
    pulse: toArray("Floating-Empty or Leather"),
    key_symptoms: toArray("Poor bone development in children, Weakness of knees, Falling hair, Poor memory"),
    treatment_principle: toArray("Nourish Essence, Tonify Kidneys"),
    acupuncture_points: parsePoints("KI-3, KI-6, CV-4, BL-23, DU-4, DU-14, DU-20, GB-39"),
  },
  {
    id: "KIDNEY_QI_NOT_FIRM",
    name_id: "Qi Ginjal Tidak Kuat (Tidak Menahan)",
    name_en: "Kidney Qi Not Firm",
    primary_organs: ["Kidney"],
    wuxing_element: "Water",
    pattern_type: "deficiency",
    clinical_manifestations: toArray("Soreness and weakness of the lower back, Weak knees, Clear and frequent urination, Weak stream urination, Dribbling after urination, Incontinence of urine, Enuresis, Urination at night, Nocturnal emissions without dreams, Premature ejaculation, Spermatorrhoea, Prolapse of uterus, Chronic vaginal discharge, Dragging-down feeling in the lower abdomen, Recurrent miscarriages"),
    tongue: toArray("Pale"),
    pulse: toArray("Deep-Weak, especially in the rear positions"),
    key_symptoms: toArray("Frequent pale urination, Weak stream, Lower backache"),
    treatment_principle: toArray("Tonify and warm the Kidneys, Consolidate Qi, Astringe Essence"),
    acupuncture_points: parsePoints("KI-3, BL-23, DU-4, CV-4, CV-6, BL-52, GV-4"),
  },
  {
    id: "DAMP_HEAT_BLADDER",
    name_id: "Lembap-Panas Kandung Kemih",
    name_en: "Damp-Heat in the Bladder",
    primary_organs: ["Bladder"],
    wuxing_element: "Water",
    pattern_type: "excess_damp_heat",
    clinical_manifestations: toArray("Burning on urination, Frequent and urgent urination, Scanty-dark urine, Blood in urine, Sand in urine, Fever, Thirst with no desire to drink, Hypogastric fullness/pain"),
    tongue: toArray("Red body, Thick sticky yellow coating (on the root)"),
    pulse: toArray("Slippery, Rapid"),
    key_symptoms: toArray("Burning urination, Dark urine, Thick sticky yellow coating at root"),
    treatment_principle: toArray("Resolve Dampness, Clear Heat, Open Water Passages"),
    acupuncture_points: parsePoints("SP-9, SP-6, BL-28, CV-3, BL-22, ST-28"),
  }
];

export const TCM_DB: TcmDatabase = {
  metadata: {
    db_name: "Maciocia Full Syndromes 2026",
    version: "3.0",
    sources_used: ["Foundations of Chinese Medicine 3rd Ed."],
    scope_note: "Core syndromes and protocols for clinical CDSS."
  },
  clinical_config: {},
  patient_form_schema: {},
  core_rules: {},
  wuxing_map: {
    "Wood": ["Liver", "Gall Bladder"],
    "Fire": ["Heart", "Small Intestine", "Pericardium", "San Jiao"],
    "Earth": ["Spleen", "Stomach"],
    "Metal": ["Lung", "Large Intestine"],
    "Water": ["Kidney", "Bladder"]
  },
  organ_details: {
    "Liver": {
      name: "Liver", type: "Zang", element: "Wood",
      main_functions: ["Stores Blood", "Ensures smooth flow of Qi", "Controls tendons", "Manifests in the eyes"],
      emotion: "Anger", season: "Spring", sense_organ: "Eyes", tissues: "Tendons", flavor: "Sour", color: "Green/Blue", time_of_day: "1-3 AM"
    },
    "Heart": {
      name: "Heart", type: "Zang", element: "Fire",
      main_functions: ["Governs Blood", "Controls the blood vessels", "Houses the Mind (Shen)", "Manifests in the complexion"],
      emotion: "Joy", season: "Summer", sense_organ: "Tongue", tissues: "Blood vessels", flavor: "Bitter", color: "Red", time_of_day: "11 AM - 1 PM"
    },
    "Spleen": {
      name: "Spleen", type: "Zang", element: "Earth",
      main_functions: ["Governs transformation and transportation", "Controls Blood", "Controls the muscles and the four limbs", "Opens into the mouth"],
      emotion: "Pensiveness/Worry", season: "Late Summer", sense_organ: "Mouth", tissues: "Muscles", flavor: "Sweet", color: "Yellow", time_of_day: "9-11 AM"
    },
    "Lung": {
      name: "Lung", type: "Zang", element: "Metal",
      main_functions: ["Governs Qi and respiration", "Controls channels and blood vessels", "Controls diffusing and descending", "Regulates water passages"],
      emotion: "Sadness/Grief", season: "Autumn", sense_organ: "Nose", tissues: "Skin", flavor: "Pungent", color: "White", time_of_day: "3-5 AM"
    },
    "Kidney": {
      name: "Kidney", type: "Zang", element: "Water",
      main_functions: ["Stores Essence (Jing)", "Governs birth, growth, reproduction and development", "Produces Marrow", "Governs Water"],
      emotion: "Fear", season: "Winter", sense_organ: "Ears", tissues: "Bones", flavor: "Salty", color: "Black/Dark Blue", time_of_day: "5-7 PM"
    }
  },
  special_point_tables: {},
  syndromes: {
    FILLED_FROM_PDF: [...MACIOCIA_SYNDROMES],
    TODO_FROM_PDF: [...MACIOCIA_100_PATTERNS] as Syndrome[]
  },
  herbal_guidelines: {
    per_syndrome_overrides_for_current_DB_snippet: {},
    herbal_rules_by_pattern_type: {
      "full_heat_excess": { suggest_chief: ["Huang Lian", "Zhi Zi"], notes: "Clear Heat Formula" },
      "excess_cold": { suggest_chief: ["Gan Jiang", "Rou Gui"], notes: "Warm Internal Formula" }
    }
  },
  stroke_protocols: {
    etiologies: [
      { name: "Wind-Stroke (Meridians)", pathogen: "Wind", points: ["GV-20", "GB-20"], focus: "Expel Wind" }
    ],
    scalp_zones: [
      { name: "Motor Area", desc: "For motor paralysis on contralateral side" }
    ],
    jins_three_needles: [
      { name: "Nie San Zhen", points: ["Temporal Points"], indication: "Motor/Speech issues" }
    ],
    research_highlights: [
      { context: "Neuroplasticity", mechanism: "Scalp acupuncture increases BDNF", effect: "Improved motor recovery" }
    ],
    case_studies: [
      { title: "Post-Ischemic Stroke", patient_profile: "65yo Male", history: "Right sided hemiparesis", diagnosis: "Liver Wind", points_used: ["GV-20", "ST-36"], results: ["Significant improvement in gait"] }
    ]
  }
};
