import { Syndrome } from './types';

// Helper to parse strings into arrays for the DB
const toArray = (str: string) => str.split(/[,;]\s?/).map(s => s.trim()).filter(s => s);

export const MACIOCIA_100_PATTERNS: Partial<Syndrome>[] = [
  // Pola Organ Jantung (Heart Patterns)
  { id: "HEART_QI_DEFICIENCY", name_en: "Heart-Qi Deficiency", diagnostic_tip: "Palpitasi, sesak napas saat beraktivitas.", primary_organs: ["Heart"], wuxing_element: "Fire", treatment_principle: ["Tonify Heart Qi"], acupuncture_points: ["HT5","PC6","BL15","CV17"], herbal_prescription: "Bao Yuan Tang" },
  { id: "HEART_YANG_DEFICIENCY", name_en: "Heart-Yang Deficiency", diagnostic_tip: "Gejala defisiensi Qi ditambah perasaan dingin.", primary_organs: ["Heart"], wuxing_element: "Fire", treatment_principle: ["Tonify and warm Heart Yang"], acupuncture_points: ["HT5","PC6","BL15","CV17","CV14","GV14"], herbal_prescription: "Gui Zhi Gan Cao Long Gu Mu Li Tang" },
  { id: "HEART_YANG_COLLAPSE", name_en: "Heart-Yang Collapse", diagnostic_tip: "Kondisi darurat dengan keringat dingin dan nadi sangat lemah.", primary_organs: ["Heart"], wuxing_element: "Fire", treatment_principle: ["Rescue Yang","Restore consciousness"], acupuncture_points: ["CV4","CV8","CV6","GV4","ST36","PC6"], herbal_prescription: "Shen Fu Tang" },
  { id: "HEART_BLOOD_DEFICIENCY", name_en: "Heart-Blood Deficiency", diagnostic_tip: "Palpitasi, pusing, insomnia, daya ingat lemah.", primary_organs: ["Heart"], wuxing_element: "Fire", treatment_principle: ["Nourish Heart Blood","Calm the Mind"], acupuncture_points: ["HT7","PC6","CV14","CV15","BL15","BL17","BL20"], herbal_prescription: "Si Wu Tang or Yang Xin Tang" },
  { id: "HEART_YIN_DEFICIENCY", name_en: "Heart-Yin Deficiency", diagnostic_tip: "Palpitasi, keringat malam, panas di telapak tangan.", primary_organs: ["Heart"], wuxing_element: "Fire", treatment_principle: ["Nourish Heart Yin","Calm the Mind"], acupuncture_points: ["HT7","PC6","CV14","CV15","BL15","SP6","KD7"], herbal_prescription: "Tian Wang Bu Xin Dan" },
  { id: "HEART_FIRE_BLAZING", name_en: "Heart-Fire Blazing", diagnostic_tip: "Ulserasi lidah, haus, kegelisahan mental yang parah.", primary_organs: ["Heart"], wuxing_element: "Fire", treatment_principle: ["Clear Heart Fire","Calm the Mind"], acupuncture_points: ["HT8","HT9","CV15","BL15","PC8","SP6","KD6"], herbal_prescription: "Xie Xin Tang or Dao Chi San" },
  { id: "PHLEGM_FIRE_HARASSING_THE_HEART", name_en: "Phlegm-Fire Harassing the Heart", diagnostic_tip: "Perilaku manik, kebingungan mental, suara dahak di tenggorokan.", primary_organs: ["Heart"], wuxing_element: "Fire", treatment_principle: ["Clear Heart Fire","Resolve Phlegm","Calm the Mind"], acupuncture_points: ["PC5","HT8","HT9","CV15","BL15","ST40","GV20"], herbal_prescription: "Wen Dan Tang or Meng Shi Gun Tan Wan" },
  { id: "PHLEGM_MISTING_THE_MIND", name_en: "Phlegm Misting the Mind", diagnostic_tip: "Kesadaran menurun, mental tumpul, berbicara sendiri.", primary_organs: ["Heart"], wuxing_element: "Fire", treatment_principle: ["Open the Orifices","Resolve Phlegm","Calm the Mind"], acupuncture_points: ["PC5","HT9","CV15","BL15","ST40","GV26"], herbal_prescription: "Di Tan Tang" },
  { id: "HEART_BLOOD_STASIS", name_en: "Heart-Blood Stasis", diagnostic_tip: "Nyeri tusuk di dada yang menjalar ke lengan kiri.", primary_organs: ["Heart"], wuxing_element: "Fire", treatment_principle: ["Move Blood","Eliminate stasis","Stop pain"], acupuncture_points: ["PC6","PC4","HT7","HT5","CV14","BL15","BL17","SP10"], herbal_prescription: "Xue Fu Zhu Yu Tang" },
  { id: "HEART_QI_STAGNATION", name_en: "Heart-Qi Stagnation", diagnostic_tip: "Perasaan tertekan di dada, sering mendesah.", primary_organs: ["Heart"], wuxing_element: "Fire", treatment_principle: ["Move Heart Qi","Open the chest"], acupuncture_points: ["PC6","CV17","HT5","CV15","BL15"], herbal_prescription: "Mu Xiang Shun Qi Wan" },

  // Pola Organ Perikardium (Pericardium Patterns)
  { id: "PERICARDIUM_BLOOD_DEFICIENCY", name_en: "Pericardium-Blood Deficiency", diagnostic_tip: "Dada tidak nyaman, palpitasi, insomnia.", primary_organs: ["Pericardium"], wuxing_element: "Fire", treatment_principle: ["Nourish Pericardium Blood","Calm the Mind"], acupuncture_points: ["PC6","HT7","CV14","BL14","BL17"], herbal_prescription: "Si Wu Tang" },
  { id: "PERICARDIUM_FIRE", name_en: "Pericardium-Fire", diagnostic_tip: "Rasa sesak di dada, haus, rasa pahit.", primary_organs: ["Pericardium"], wuxing_element: "Fire", treatment_principle: ["Clear Pericardium Fire","Calm the Mind"], acupuncture_points: ["PC8","PC3","HT8","CV14","BL14"], herbal_prescription: "Xie Xin Tang" },
  { id: "PHLEGM_FIRE_HARASSING_THE_PERICARDIUM", name_en: "Phlegm-Fire Harassing the Pericardium", diagnostic_tip: "Gejala mental parah dengan dahak.", primary_organs: ["Pericardium"], wuxing_element: "Fire", treatment_principle: ["Clear Pericardium Fire","Resolve Phlegm","Calm the Mind"], acupuncture_points: ["PC5","PC8","CV15","ST40","BL14"], herbal_prescription: "Wen Dan Tang" },
  { id: "HEAT_IN_THE_PERICARDIUM", name_en: "Heat in the Pericardium", diagnostic_tip: "Demam di malam hari, delirium (pada penyakit demam).", primary_organs: ["Pericardium"], wuxing_element: "Fire", treatment_principle: ["Clear Ying-level Heat","Calm the Mind"], acupuncture_points: ["PC9","PC8","HT9","KD6","CV14"], herbal_prescription: "Qing Ying Tang" },
  { id: "PERICARDIUM_BLOOD_STASIS", name_en: "Pericardium-Blood Stasis", diagnostic_tip: "Nyeri dada yang tajam, bibir ungu.", primary_organs: ["Pericardium"], wuxing_element: "Fire", treatment_principle: ["Move Blood","Eliminate stasis in Pericardium"], acupuncture_points: ["PC6","PC4","CV14","BL14","BL17","SP10"], herbal_prescription: "Xue Fu Zhu Yu Tang" },

  // Pola Organ Hati (Liver Patterns)
  { id: "LIVER_QI_STAGNATION", name_en: "Liver-Qi Stagnation", diagnostic_tip: "Distensi hipokondrium, depresi, perasaan terganjal di tenggorokan.", primary_organs: ["Liver"], wuxing_element: "Wood", treatment_principle: ["Smooth Liver Qi","Resolve stagnation"], acupuncture_points: ["LR3","GB34","LR13","LR14","TE6","PC6"], herbal_prescription: "Xiao Yao San or Chai Hu Shu Gan San" },
  { id: "STAGNANT_LIVER_QI_TURNING_INTO_HEAT", name_en: "Stagnant Liver-Qi turning into Heat", diagnostic_tip: "Gejala stagnasi ditambah iritabilitas dan wajah merah.", primary_organs: ["Liver"], wuxing_element: "Wood", treatment_principle: ["Smooth Liver Qi","Clear Liver Heat"], acupuncture_points: ["LR3","LR2","GB34","LR14","TE6"], herbal_prescription: "Dan Zhi Xiao Yao San" },
  { id: "REBELLIOUS_LIVER_QI", name_en: "Rebellious Liver-Qi", diagnostic_tip: "Sakit kepala, pusing, sendawa.", primary_organs: ["Liver"], wuxing_element: "Wood", treatment_principle: ["Subdue rebellious Liver Qi"], acupuncture_points: ["LR3","LR14","PC6","ST36","GB34"], herbal_prescription: "Si Ni San" },
  { id: "LIVER_BLOOD_STASIS", name_en: "Liver-Blood Stasis", diagnostic_tip: "Nyeri tajam, massa di perut, periode menstruasi menyakitkan dengan darah gelap.", primary_organs: ["Liver"], wuxing_element: "Wood", treatment_principle: ["Move Liver Blood","Eliminate stasis"], acupuncture_points: ["LR3","GB34","BL18","BL17","SP10","CV6"], herbal_prescription: "Ge Xia Zhu Yu Tang" },
  { id: "LIVER_FIRE_BLAZING", name_en: "Liver-Fire Blazing", diagnostic_tip: "Sakit kepala berdenyut, mata merah, amarah meledak-ledak.", primary_organs: ["Liver"], wuxing_element: "Wood", treatment_principle: ["Clear Liver Fire"], acupuncture_points: ["LR2","LR3","GB20","GB34","BL18"], herbal_prescription: "Long Dan Xie Gan Tang" },
  { id: "DAMP_HEAT_IN_THE_LIVER", name_en: "Damp-Heat in the Liver", diagnostic_tip: "Kulit kuning (jaundice), rasa mual, distensi perut.", primary_organs: ["Liver"], wuxing_element: "Wood", treatment_principle: ["Resolve Dampness","Clear Liver Heat"], acupuncture_points: ["LR14","GB34","BL18","CV12","SP9","LR2"], herbal_prescription: "Long Dan Xie Gan Tang" },
  { id: "STAGNATION_OF_COLD_IN_THE_LIVER_CHANNEL", name_en: "Stagnation of Cold in the Liver Channel", diagnostic_tip: "Nyeri di area genital atau hernia yang membaik dengan panas.", primary_organs: ["Liver"], wuxing_element: "Wood", treatment_principle: ["Warm the Liver channel","Disperse Cold"], acupuncture_points: ["LR5","LR1","CV3","LR3"], herbal_prescription: "Nuan Gan Jian" },
  { id: "LIVER_BLOOD_DEFICIENCY", name_en: "Liver-Blood Deficiency", diagnostic_tip: "Pandangan kabur, kuku rapuh, menstruasi sedikit.", primary_organs: ["Liver"], wuxing_element: "Wood", treatment_principle: ["Nourish Liver Blood"], acupuncture_points: ["LR8","ST36","SP6","BL18","BL20"], herbal_prescription: "Si Wu Tang or Shao Yao Gan Cao Tang" },
  { id: "LIVER_YIN_DEFICIENCY", name_en: "Liver-Yin Deficiency", diagnostic_tip: "Mata kering, pusing, rasa panas di wajah.", primary_organs: ["Liver"], wuxing_element: "Wood", treatment_principle: ["Nourish Liver Yin"], acupuncture_points: ["LR8","SP6","KD3","BL18","BL23"], herbal_prescription: "Yi Guan Jian" },
  { id: "LIVER_YANG_RISING", name_en: "Liver-Yang Rising", diagnostic_tip: "Sakit kepala di pelipis, tinnitus, mudah marah.", primary_organs: ["Liver"], wuxing_element: "Wood", treatment_principle: ["Subdue Liver Yang","Nourish Yin"], acupuncture_points: ["LR3","GB20","KD3","SP6","LR8","BL18"], herbal_prescription: "Tian Ma Gou Teng Yin" },
  { id: "LIVER_WIND_EXTREME_HEAT_GENERATING_WIND", name_en: "Liver-Wind: Extreme Heat generating Wind", diagnostic_tip: "Kejang, leher kaku, demam tinggi.", primary_organs: ["Liver"], wuxing_element: "Wood", treatment_principle: ["Clear Heat","Extinguish Wind"], acupuncture_points: ["LR3","GV20","GV16","GB20","GV14","LR2"], herbal_prescription: "Ling Jiao Gou Teng Tang" },
  { id: "LIVER_WIND_LIVER_YANG_RISING_GENERATING_WIND", name_en: "Liver-Wind: Liver-Yang Rising generating Wind", diagnostic_tip: "Tremor, pusing parah, mati rasa.", primary_organs: ["Liver"], wuxing_element: "Wood", treatment_principle: ["Subdue Liver Yang","Extinguish Wind","Nourish Yin"], acupuncture_points: ["LR3","GV20","GB20","KD3","SP6"], herbal_prescription: "Zhen Gan Xi Feng Tang" },
  { id: "LIVER_WIND_LIVER_FIRE_GENERATING_WIND", name_en: "Liver-Wind: Liver-Fire generating Wind", diagnostic_tip: "Gejala api hati disertai tremor.", primary_organs: ["Liver"], wuxing_element: "Wood", treatment_principle: ["Clear Liver Fire","Extinguish Wind"], acupuncture_points: ["LR2","LR3","GV20","GB20"], herbal_prescription: "Long Dan Xie Gan Tang with Tian Ma, Gou Teng" },
  { id: "LIVER_WIND_LIVER_BLOOD_DEFICIENCY_GENERATING_WIND", name_en: "Liver-Wind: Liver-Blood Deficiency generating Wind", diagnostic_tip: "Tremor ringan, otot berkedut.", primary_organs: ["Liver"], wuxing_element: "Wood", treatment_principle: ["Nourish Liver Blood","Extinguish Wind"], acupuncture_points: ["LR8","SP6","ST36","GV20","LR3"], herbal_prescription: "E Jiao Ji Zi Huang Tang" },

  // Pola Organ Paru (Lung Patterns)
  { id: "LUNG_QI_DEFICIENCY", name_en: "Lung-Qi Deficiency", diagnostic_tip: "Batuk lemah, suara pelan, mudah lelah.", primary_organs: ["Lung"], wuxing_element: "Metal", treatment_principle: ["Tonify Lung Qi"], acupuncture_points: ["LU9","LU7","CV6","BL13","ST36"], herbal_prescription: "Bu Fei Tang or Yu Ping Feng San" },
  { id: "LUNG_YIN_DEFICIENCY", name_en: "Lung-Yin Deficiency", diagnostic_tip: "Batuk kering, suara serak, keringat malam.", primary_organs: ["Lung"], wuxing_element: "Metal", treatment_principle: ["Nourish Lung Yin"], acupuncture_points: ["LU9","CV4","KD6","SP6","BL13","BL43"], herbal_prescription: "Bai He Gu Jin Tang" },
  { id: "LUNG_DRYNESS", name_en: "Lung-Dryness", diagnostic_tip: "Batuk kering, mulut dan tenggorokan kering.", primary_organs: ["Lung"], wuxing_element: "Metal", treatment_principle: ["Moisten the Lungs","Nourish Fluids"], acupuncture_points: ["LU9","CV4","KD6","SP6","BL13"], herbal_prescription: "Qing Zao Jiu Fei Tang" },
  { id: "WIND_COLD_INVADING_THE_LUNGS", name_en: "Wind-Cold Invading the Lungs", diagnostic_tip: "Bersin, pilek cair bening, benci dingin.", primary_organs: ["Lung"], wuxing_element: "Metal", treatment_principle: ["Release the Exterior","Disperse Cold","Restore Lung Qi descending"], acupuncture_points: ["LU7","BL12","GV16","LI4"], herbal_prescription: "Jing Fang Bai Du San" },
  { id: "WIND_HEAT_INVADING_THE_LUNGS", name_en: "Wind-Heat Invading the Lungs", diagnostic_tip: "Demam, sakit tenggorokan, dahak kuning.", primary_organs: ["Lung"], wuxing_element: "Metal", treatment_principle: ["Release the Exterior","Clear Heat","Restore Lung Qi descending"], acupuncture_points: ["LU7","LI4","LI11","GV14","BL12","LU11"], herbal_prescription: "Yin Qiao San" },
  { id: "WIND_WATER_INVADING_THE_LUNGS", name_en: "Wind-Water Invading the Lungs", diagnostic_tip: "Edema tiba-tiba di wajah.", primary_organs: ["Lung"], wuxing_element: "Metal", treatment_principle: ["Release the Exterior","Resolve Dampness","Restore Lung Qi descending"], acupuncture_points: ["LU7","LI4","LI6","BL12","CV9","BL13"], herbal_prescription: "Yue Bi Tang" },
  { id: "DAMP_PHLEGM_IN_THE_LUNGS", name_en: "Damp-Phlegm in the Lungs", diagnostic_tip: "Batuk kronis dengan banyak dahak putih mudah keluar.", primary_organs: ["Lung"], wuxing_element: "Metal", treatment_principle: ["Resolve Phlegm","Restore Lung Qi descending"], acupuncture_points: ["LU5","LU7","ST40","CV12","BL13","SP3"], herbal_prescription: "Er Chen Tang" },
  { id: "COLD_PHLEGM_IN_THE_LUNGS", name_en: "Cold-Phlegm in the Lungs", diagnostic_tip: "Batuk dengan dahak putih encer, anggota gerak dingin.", primary_organs: ["Lung"], wuxing_element: "Metal", treatment_principle: ["Warm the Lungs","Resolve Phlegm"], acupuncture_points: ["LU5","LU7","ST40","CV12","BL13","CV17"], herbal_prescription: "Ling Gui Zhu Gan Tang" },
  { id: "PHLEGM_HEAT_IN_THE_LUNGS", name_en: "Phlegm-Heat in the Lungs", diagnostic_tip: "Batuk dengan dahak kuning kental, sesak napas.", primary_organs: ["Lung"], wuxing_element: "Metal", treatment_principle: ["Clear Lung Heat","Resolve Phlegm"], acupuncture_points: ["LU5","LU7","LU10","LI11","ST40","BL13"], herbal_prescription: "Qing Qi Hua Tan Wan" },
  { id: "DRY_PHLEGM_IN_THE_LUNGS", name_en: "Dry-Phlegm in the Lungs", diagnostic_tip: "Batuk sulit mengeluarkan sedikit dahak kental.", primary_organs: ["Lung"], wuxing_element: "Metal", treatment_principle: ["Moisten the Lungs","Resolve Phlegm"], acupuncture_points: ["LU9","LU5","ST40","CV12","BL13","KD6"], herbal_prescription: "Mai Men Dong Tang" },
  { id: "PHLEGM_FLUIDS_OBSTRUCTING_THE_LUNGS", name_en: "Phlegm-Fluids obstructing the Lungs", diagnostic_tip: "Batuk dengan dahak encer berbusa.", primary_organs: ["Lung"], wuxing_element: "Metal", treatment_principle: ["Resolve Phlegm","Warm the Lungs","Transform Fluids"], acupuncture_points: ["LU5","LU9","ST40","CV12","BL13","CV9"], herbal_prescription: "Ting Li Da Zao Xie Fei Tang" },

  // Pola Organ Limpa (Spleen Patterns)
  { id: "SPLEEN_QI_DEFICIENCY", name_en: "Spleen-Qi Deficiency", diagnostic_tip: "Nafsu makan buruk, tinja lembek, kelelahan kronis.", primary_organs: ["Spleen"], wuxing_element: "Earth", treatment_principle: ["Tonify Spleen Qi"], acupuncture_points: ["SP3","SP6","ST36","CV12","BL20"], herbal_prescription: "Si Jun Zi Tang or Shen Ling Bai Zhu San" },
  { id: "SPLEEN_YANG_DEFICIENCY", name_en: "Spleen-Yang Deficiency", diagnostic_tip: "Gejala defisiensi Qi ditambah perasaan dingin.", primary_organs: ["Spleen"], wuxing_element: "Earth", treatment_principle: ["Tonify and warm Spleen Yang"], acupuncture_points: ["SP3","SP6","ST36","CV12","BL20","CV9"], herbal_prescription: "Li Zhong Wan" },
  { id: "SPLEEN_QI_SINKING", name_en: "Spleen-Qi Sinking", diagnostic_tip: "Prolaps organ (rahim, anus), perasaan turun di perut.", primary_organs: ["Spleen"], wuxing_element: "Earth", treatment_principle: ["Tonify Spleen Qi","Raise Qi"], acupuncture_points: ["SP3","ST36","CV12","BL20","GV20","CV6"], herbal_prescription: "Bu Zhong Yi Qi Tang" },
  { id: "SPLEEN_NOT_CONTROLLING_BLOOD", name_en: "Spleen Not Controlling Blood", diagnostic_tip: "Memar mudah terjadi, darah dalam tinja atau urin.", primary_organs: ["Spleen"], wuxing_element: "Earth", treatment_principle: ["Tonify Spleen Qi","Hold Blood"], acupuncture_points: ["SP3","SP6","SP10","ST36","BL20","BL17"], herbal_prescription: "Gui Pi Tang" },
  { id: "SPLEEN_BLOOD_DEFICIENCY", name_en: "Spleen-Blood Deficiency", diagnostic_tip: "Wajah pucat, pusing, gejala pencernaan buruk.", primary_organs: ["Spleen"], wuxing_element: "Earth", treatment_principle: ["Tonify Spleen Qi","Nourish Blood"], acupuncture_points: ["SP3","SP6","ST36","CV4","BL20","BL17"], herbal_prescription: "Gui Pi Tang" },
  { id: "COLD_DAMPNESS_INVADING_THE_SPLEEN", name_en: "Cold-Dampness Invading the Spleen", diagnostic_tip: "Perasaan berat, mual, lidah dengan lapisan putih lengket.", primary_organs: ["Spleen"], wuxing_element: "Earth", treatment_principle: ["Resolve Dampness","Warm the Spleen"], acupuncture_points: ["SP9","SP3","ST36","CV12","BL20","ST8"], herbal_prescription: "Wei Ling Tang" },
  { id: "DAMP_HEAT_INVADING_THE_SPLEEN", name_en: "Damp-Heat Invading the Spleen", diagnostic_tip: "Kepenuhan di perut, mual, kulit kuning.", primary_organs: ["Spleen"], wuxing_element: "Earth", treatment_principle: ["Resolve Dampness","Clear Heat"], acupuncture_points: ["SP9","SP6","LI11","CV12","BL20","GB34"], herbal_prescription: "Lian Po Yin" },

  // Pola Organ Ginjal (Kidney Patterns)
  { id: "KIDNEY_YANG_DEFICIENCY", name_en: "Kidney-Yang Deficiency", diagnostic_tip: "Sakit punggung bawah, lutut dingin, impotensi.", primary_organs: ["Kidney"], wuxing_element: "Water", treatment_principle: ["Tonify and warm Kidney Yang"], acupuncture_points: ["KD3","KD7","BL23","GV4","CV4","CV6"], herbal_prescription: "Jin Gui Shen Qi Wan or You Gui Wan" },
  { id: "KIDNEY_YIN_DEFICIENCY", name_en: "Kidney-Yin Deficiency", diagnostic_tip: "Pusing, tinnitus, keringat malam.", primary_organs: ["Kidney"], wuxing_element: "Water", treatment_principle: ["Nourish Kidney Yin"], acupuncture_points: ["KD3","KD6","SP6","BL23","CV4"], herbal_prescription: "Liu Wei Di Huang Wan or Zuo Gui Wan" },
  { id: "KIDNEY_QI_NOT_FIRM", name_en: "Kidney-Qi Not Firm", diagnostic_tip: "Urin menetes, sering buang air kecil, ejakulasi dini.", primary_organs: ["Kidney"], wuxing_element: "Water", treatment_principle: ["Tonify and stabilize Kidney Qi"], acupuncture_points: ["KD3","BL23","GV4","CV4","CV6","GV20"], herbal_prescription: "Suo Quan Wan" },
  { id: "KIDNEY_FAILING_TO_RECEIVE_QI", name_en: "Kidney Failing to Receive Qi", diagnostic_tip: "Sesak napas saat aktivitas, urin bening saat serangan asma.", primary_organs: ["Kidney"], wuxing_element: "Water", treatment_principle: ["Tonify Kidneys","Grasp Qi"], acupuncture_points: ["KD3","KD7","BL23","CV4","CV6","LU7","KD6"], herbal_prescription: "Du Qi Wan" },
  { id: "KIDNEY_ESSENCE_DEFICIENCY", name_en: "Kidney-Essence Deficiency", diagnostic_tip: "Perkembangan tulang buruk pada anak, penuaan dini pada dewasa.", primary_organs: ["Kidney"], wuxing_element: "Water", treatment_principle: ["Nourish Kidney Essence"], acupuncture_points: ["KD3","KD6","BL23","GV4","CV4","GB39","BL11"], herbal_prescription: "He Che Da Zao Wan" },
  { id: "KIDNEY_YANG_DEFICIENCY_WATER_OVERFLOWING", name_en: "Kidney-Yang Deficiency, Water Overflowing", diagnostic_tip: "Edema parah di kaki, palpitasi atau asma.", primary_organs: ["Kidney"], wuxing_element: "Water", treatment_principle: ["Warm Kidney Yang","Transform Water"], acupuncture_points: ["KD3","KD7","BL23","CV9","CV4","ST28","SP9"], herbal_prescription: "Zhen Wu Tang" },

  // Pola Organ Lambung (Stomach Patterns)
  { id: "STOMACH_QI_DEFICIENCY", name_en: "Stomach-Qi Deficiency", diagnostic_tip: "Ketidaknyamanan ringan di epigastrium, kelelahan.", primary_organs: ["Stomach"], wuxing_element: "Earth", treatment_principle: ["Tonify Stomach Qi"], acupuncture_points: ["ST36","CV12","BL21","SP3"], herbal_prescription: "Xiang Sha Liu Jun Zi Tang" },
  { id: "STOMACH_DEFICIENT_COLD", name_en: "Stomach-Deficient Cold", diagnostic_tip: "Nyeri perut yang membaik dengan panas dan makan.", primary_organs: ["Stomach"], wuxing_element: "Earth", treatment_principle: ["Warm the Stomach","Tonify Stomach Qi"], acupuncture_points: ["ST36","CV12","BL21","SP3","CV6"], herbal_prescription: "Huang Qi Jian Zhong Tang" },
  { id: "STOMACH_YIN_DEFICIENCY", name_en: "Stomach-Yin Deficiency", diagnostic_tip: "Epigastrium kering, haus tapi tidak ingin minum banyak.", primary_organs: ["Stomach"], wuxing_element: "Earth", treatment_principle: ["Nourish Stomach Yin"], acupuncture_points: ["ST36","CV12","SP6","KD3"], herbal_prescription: "Yi Wei Tang" },
  { id: "STOMACH_QI_STAGNATION", name_en: "Stomach-Qi Stagnation", diagnostic_tip: "Distensi dan nyeri di epigastrium.", primary_organs: ["Stomach"], wuxing_element: "Earth", treatment_principle: ["Move Stomach Qi","Eliminate stagnation"], acupuncture_points: ["ST36","CV12","ST34","PC6","LR3"], herbal_prescription: "Chai Hu Shu Gan San" },
  { id: "STOMACH_FIRE", name_en: "Stomach-Fire (Stomach-Heat)", diagnostic_tip: "Nyeri terbakar, gusi berdarah, napas bau.", primary_organs: ["Stomach"], wuxing_element: "Earth", treatment_principle: ["Clear Stomach Fire"], acupuncture_points: ["ST44","ST34","ST21","CV12","LI11"], herbal_prescription: "Qing Wei San" },
  { id: "DAMP_HEAT_IN_THE_STOMACH", name_en: "Damp-Heat in the Stomach", diagnostic_tip: "Rasa penuh, mual, rasa lengket di mulut.", primary_organs: ["Stomach"], wuxing_element: "Earth", treatment_principle: ["Resolve Dampness","Clear Stomach Heat"], acupuncture_points: ["ST44","ST34","CV12","SP9","LI11"], herbal_prescription: "Lian Po Yin" },
  { id: "COLD_INVADING_THE_STOMACH", name_en: "Cold Invading the Stomach", diagnostic_tip: "Nyeri hebat tiba-tiba di perut, muntah cairan bening.", primary_organs: ["Stomach"], wuxing_element: "Earth", treatment_principle: ["Disperse Cold","Warm the Stomach"], acupuncture_points: ["ST36","CV12","ST21","SP4"], herbal_prescription: "Li Zhong Wan" },
  { id: "STOMACH_QI_REBELLING_UPWARDS", name_en: "Stomach-Qi Rebelling Upwards", diagnostic_tip: "Sendawa, mual, cegukan.", primary_organs: ["Stomach"], wuxing_element: "Earth", treatment_principle: ["Subdue rebellious Stomach Qi"], acupuncture_points: ["ST36","CV12","PC6","SP4","CV13"], herbal_prescription: "Xuan Fu Dai Zhe Tang" },
  { id: "RETENTION_OF_FOOD_IN_THE_STOMACH", name_en: "Retention of Food in the Stomach", diagnostic_tip: "Insomnia, bau mulut, nyeri perut memburuk setelah makan.", primary_organs: ["Stomach"], wuxing_element: "Earth", treatment_principle: ["Resolve food retention","Move Stomach Qi"], acupuncture_points: ["ST36","CV12","ST21","ST44","SP4","CV10"], herbal_prescription: "Bao He Wan" },
  { id: "STOMACH_BLOOD_STASIS", name_en: "Stomach-Blood Stasis", diagnostic_tip: "Nyeri tusuk hebat di epigastrium, muntah darah.", primary_organs: ["Stomach"], wuxing_element: "Earth", treatment_principle: ["Move Blood","Eliminate stasis in the Stomach"], acupuncture_points: ["ST36","CV12","ST34","SP10","BL17","PC6"], herbal_prescription: "Shi Xiao San" },

  // Pola Usus Besar, Usus Kecil, dan Kandung Kemih
  { id: "DAMP_HEAT_IN_THE_LARGE_INTESTINE", name_en: "Damp-Heat in the Large Intestine", diagnostic_tip: "Nyeri perut, diare dengan lendir dan darah.", primary_organs: ["Large Intestine"], wuxing_element: "Metal", treatment_principle: ["Clear Heat","Resolve Dampness in Large Intestine"], acupuncture_points: ["ST37","ST25","LI11","SP9","BL25"], herbal_prescription: "Bai Tou Weng Tang" },
  { id: "HEAT_IN_THE_LARGE_INTESTINE", name_en: "Heat in the Large Intestine", diagnostic_tip: "Konstipasi, tinja kering, sensasi terbakar di anus.", primary_organs: ["Large Intestine"], wuxing_element: "Metal", treatment_principle: ["Clear Heat in Large Intestine","Promote bowel movement"], acupuncture_points: ["ST37","ST25","LI11","TE6","BL25"], herbal_prescription: "Ma Zi Ren Wan" },
  { id: "HEAT_OBSTRUCTING_THE_LARGE_INTESTINE", name_en: "Heat Obstructing the Large Intestine", diagnostic_tip: "Konstipasi hebat dengan demam tinggi.", primary_organs: ["Large Intestine"], wuxing_element: "Metal", treatment_principle: ["Clear Heat","Remove obstruction in Large Intestine"], acupuncture_points: ["ST37","ST25","LI11","TE6","BL25","ST39"], herbal_prescription: "Da Cheng Qi Tang" },
  { id: "COLD_INVADING_THE_LARGE_INTESTINE", name_en: "Cold Invading the Large Intestine", diagnostic_tip: "Diare mendadak dengan nyeri perut.", primary_organs: ["Large Intestine"], wuxing_element: "Metal", treatment_principle: ["Disperse Cold","Warm the Large Intestine"], acupuncture_points: ["ST37","ST25","CV6","ST36"], herbal_prescription: "Li Zhong Wan" },
  { id: "LARGE_INTESTINE_QI_STAGNATION", name_en: "Large Intestine-Qi Stagnation", diagnostic_tip: "Distensi perut, tinja seperti kotoran kambing.", primary_organs: ["Large Intestine"], wuxing_element: "Metal", treatment_principle: ["Move Qi in Large Intestine"], acupuncture_points: ["ST37","ST25","CV6","LR3","TE6"], herbal_prescription: "Si Mo Tang" },
  { id: "LARGE_INTESTINE_DRYNESS", name_en: "Large Intestine-Dryness", diagnostic_tip: "Konstipasi kronis dengan tinja sangat kering.", primary_organs: ["Large Intestine"], wuxing_element: "Metal", treatment_principle: ["Moisten Large Intestine","Promote bowel movement"], acupuncture_points: ["ST37","ST25","KD6","SP6","TE6"], herbal_prescription: "Run Chang Wan" },
  { id: "LARGE_INTESTINE_COLD", name_en: "Large Intestine-Cold (Deficiency)", diagnostic_tip: "Diare kronis, kelelahan setelah buang air besar.", primary_organs: ["Large Intestine"], wuxing_element: "Metal", treatment_principle: ["Warm and tonify Large Intestine"], acupuncture_points: ["ST37","ST25","CV6","ST36","BL25"], herbal_prescription: "Li Zhong Wan" },
  { id: "FULL_HEAT_IN_THE_SMALL_INTESTINE", name_en: "Full-Heat in the Small Intestine", diagnostic_tip: "Urin gelap dan nyeri, ulserasi mulut.", primary_organs: ["Small Intestine"], wuxing_element: "Fire", treatment_principle: ["Clear Heat in Small Intestine and Heart"], acupuncture_points: ["SI2","SI5","HT8","ST39","CV4"], herbal_prescription: "Dao Chi San" },
  { id: "SMALL_INTESTINE_QI_PAIN", name_en: "Small Intestine-Qi Pain", diagnostic_tip: "Nyeri perut yang melilit hingga ke punggung.", primary_organs: ["Small Intestine"], wuxing_element: "Fire", treatment_principle: ["Move Qi in Small Intestine","Stop pain"], acupuncture_points: ["ST39","CV4","LR3","GB34","SP6"], herbal_prescription: "Tian Tai Wu Yao San" },
  { id: "SMALL_INTESTINE_QI_TIED", name_en: "Small Intestine-Qi Tied", diagnostic_tip: "Nyeri perut hebat, konstipasi, muntah.", primary_organs: ["Small Intestine"], wuxing_element: "Fire", treatment_principle: ["Move Qi","Remove obstruction in Small Intestine"], acupuncture_points: ["ST39","CV4","ST25","LR3","PC6"], herbal_prescription: "Da Cheng Qi Tang" },
  { id: "INFESTATION_OF_WORMS_IN_THE_SMALL_INTESTINE", name_en: "Infestation of Worms in the Small Intestine", diagnostic_tip: "Nyeri perut, gatal di hidung/anus.", primary_organs: ["Small Intestine"], wuxing_element: "Fire", treatment_principle: ["Expel worms","Harmonize intestines"], acupuncture_points: ["ST39","CV4","SP10","ST36"], herbal_prescription: "Wu Mei Wan" },
  { id: "SMALL_INTESTINE_DEFICIENT_COLD", name_en: "Small Intestine-Deficient Cold", diagnostic_tip: "Nyeri perut tumpul, diare bening.", primary_organs: ["Small Intestine"], wuxing_element: "Fire", treatment_principle: ["Warm and tonify Small Intestine"], acupuncture_points: ["ST39","CV4","CV6","ST36","BL27"], herbal_prescription: "Li Zhong Wan" },
  { id: "DAMP_HEAT_IN_THE_GALL_BLADDER", name_en: "Damp-Heat in the Gall Bladder", diagnostic_tip: "Nyeri hipokondrium, rasa pahit, mual.", primary_organs: ["Gall Bladder"], wuxing_element: "Wood", treatment_principle: ["Clear Heat","Resolve Dampness in Gall Bladder"], acupuncture_points: ["GB24","GB34","LR14","CV12","LI11","SP9"], herbal_prescription: "Long Dan Xie Gan Tang" },
  { id: "GALL_BLADDER_DEFICIENCY", name_en: "Gall Bladder-Deficiency (Timidity)", diagnostic_tip: "Pusing, penglihatan kabur, mudah takut.", primary_organs: ["Gall Bladder"], wuxing_element: "Wood", treatment_principle: ["Tonify Gall Bladder","Calm the Mind"], acupuncture_points: ["GB40","GB44","HT7","CV15","BL19"], herbal_prescription: "Wen Dan Tang" },
  { id: "DAMP_HEAT_IN_THE_BLADDER", name_en: "Damp-Heat in the Bladder", diagnostic_tip: "Urin terbakar, sulit keluar, berwarna keruh.", primary_organs: ["Bladder"], wuxing_element: "Water", treatment_principle: ["Clear Heat","Resolve Dampness in Bladder"], acupuncture_points: ["BL28","CV3","SP9","BL63","BL66"], herbal_prescription: "Ba Zheng San" },
  { id: "DAMP_COLD_IN_THE_BLADDER", name_en: "Damp-Cold in the Bladder", diagnostic_tip: "Urin sulit keluar, rasa berat di perut bawah.", primary_organs: ["Bladder"], wuxing_element: "Water", treatment_principle: ["Resolve Dampness","Disperse Cold in Bladder"], acupuncture_points: ["BL28","CV3","SP9","BL63","ST28"], herbal_prescription: "Wei Ling Tang" },
  { id: "BLADDER_DEFICIENT_COLD", name_en: "Bladder-Deficient Cold", diagnostic_tip: "Sering kencing urin bening, sakit punggung.", primary_organs: ["Bladder"], wuxing_element: "Water", treatment_principle: ["Warm and tonify Bladder"], acupuncture_points: ["BL28","CV3","CV4","KD3","GV4"], herbal_prescription: "Suo Quan Wan" },

  // Pola Gabungan dan Tahapan Penyakit (81-100)
  { id: "HEART_AND_LUNG_QI_DEFICIENCY", name_en: "Heart and Lung-Qi Deficiency", diagnostic_tip: "", primary_organs: ["Heart", "Lung"], wuxing_element: "Mixed", treatment_principle: ["Tonify Heart and Lung Qi"], acupuncture_points: ["HT5","LU9","CV17","BL15","BL13","ST36"], herbal_prescription: "Bao Yuan Tang" },
  { id: "HEART_AND_LIVER_BLOOD_DEFICIENCY", name_en: "Heart and Liver-Blood Deficiency", diagnostic_tip: "", primary_organs: ["Heart", "Liver"], wuxing_element: "Mixed", treatment_principle: ["Nourish Heart and Liver Blood"], acupuncture_points: ["HT7","LR8","SP6","BL15","BL18","CV14"], herbal_prescription: "Gui Pi Tang" },
  { id: "HEART_AND_SPLEEN_BLOOD_DEFICIENCY", name_en: "Heart and Spleen-Blood Deficiency", diagnostic_tip: "", primary_organs: ["Heart", "Spleen"], wuxing_element: "Mixed", treatment_principle: ["Tonify Spleen Qi","Nourish Heart Blood"], acupuncture_points: ["HT7","SP3","SP6","ST36","BL15","BL20"], herbal_prescription: "Gui Pi Tang" },
  { id: "HEART_AND_KIDNEY_YIN_DEFICIENCY", name_en: "Heart and Kidney-Yin Deficiency", diagnostic_tip: "", primary_organs: ["Heart", "Kidney"], wuxing_element: "Mixed", treatment_principle: ["Nourish Heart and Kidney Yin","Clear Empty Heat"], acupuncture_points: ["HT7","KD3","SP6","BL15","BL23","KD6"], herbal_prescription: "Tian Wang Bu Xin Dan" },
  { id: "HEART_AND_KIDNEY_YANG_DEFICIENCY", name_en: "Heart and Kidney-Yang Deficiency", diagnostic_tip: "", primary_organs: ["Heart", "Kidney"], wuxing_element: "Mixed", treatment_principle: ["Tonify and warm Heart and Kidney Yang"], acupuncture_points: ["HT5","KD7","BL15","BL23","CV4","GV4"], herbal_prescription: "Shen Fu Tang" },
  { id: "SPLEEN_AND_LIVER_BLOOD_DEFICIENCY", name_en: "Spleen and Liver-Blood Deficiency", diagnostic_tip: "", primary_organs: ["Spleen", "Liver"], wuxing_element: "Mixed", treatment_principle: ["Tonify Spleen Qi","Nourish Liver Blood"], acupuncture_points: ["SP3","LR8","SP6","ST36","BL20","BL18"], herbal_prescription: "Ba Zhen Tang" },
  { id: "SPLEEN_AND_LUNG_QI_DEFICIENCY", name_en: "Spleen and Lung-Qi Deficiency", diagnostic_tip: "", primary_organs: ["Spleen", "Lung"], wuxing_element: "Mixed", treatment_principle: ["Tonify Spleen and Lung Qi"], acupuncture_points: ["SP3","LU9","ST36","CV12","BL20","BL13"], herbal_prescription: "Shen Ling Bai Zhu San" },
  { id: "SPLEEN_AND_KIDNEY_YANG_DEFICIENCY", name_en: "Spleen and Kidney-Yang Deficiency", diagnostic_tip: "", primary_organs: ["Spleen", "Kidney"], wuxing_element: "Mixed", treatment_principle: ["Tonify and warm Spleen and Kidney Yang"], acupuncture_points: ["SP3","KD7","ST36","BL20","BL23","CV4","GV4"], herbal_prescription: "Zhen Wu Tang" },
  { id: "LIVER_AND_KIDNEY_YIN_DEFICIENCY", name_en: "Liver and Kidney-Yin Deficiency", diagnostic_tip: "", primary_organs: ["Liver", "Kidney"], wuxing_element: "Mixed", treatment_principle: ["Nourish Liver and Kidney Yin"], acupuncture_points: ["LR8","KD3","SP6","BL18","BL23"], herbal_prescription: "Qi Ju Di Huang Wan" },
  { id: "LIVER_FIRE_INSULTING_THE_LUNGS", name_en: "Liver-Fire Insulting the Lungs", diagnostic_tip: "", primary_organs: ["Liver", "Lung"], wuxing_element: "Mixed", treatment_principle: ["Clear Liver Fire","Moisten Lungs"], acupuncture_points: ["LR2","LU10","LU5","GB34","BL18"], herbal_prescription: "Xie Bai San with Qing Dai" },
  { id: "REBELLIOUS_LIVER_QI_INVADING_THE_SPLEEN", name_en: "Rebellious Liver-Qi Invading the Spleen", diagnostic_tip: "", primary_organs: ["Liver", "Spleen"], wuxing_element: "Mixed", treatment_principle: ["Smooth Liver Qi","Tonify Spleen"], acupuncture_points: ["LR3","LR13","GB34","SP3","ST36","CV12"], herbal_prescription: "Tong Yao Fang" },
  { id: "REBELLIOUS_LIVER_QI_INVADING_THE_STOMACH", name_en: "Rebellious Liver-Qi Invading the Stomach", diagnostic_tip: "", primary_organs: ["Liver", "Stomach"], wuxing_element: "Mixed", treatment_principle: ["Smooth Liver Qi","Harmonize Stomach"], acupuncture_points: ["LR3","LR14","GB34","ST36","CV12","PC6"], herbal_prescription: "Chai Hu Shu Gan San" },
  { id: "TAI_YANG_STAGE", name_en: "Tai Yang Stage (Greater Yang)", diagnostic_tip: "Benci dingin, sakit kepala, nadi mengambang.", primary_organs: [], wuxing_element: "Mixed", treatment_principle: ["Release the Exterior","Expel Wind-Cold"], acupuncture_points: ["BL12","LU7","LI4","GV16"], herbal_prescription: "Ma Huang Tang or Gui Zhi Tang" },
  { id: "YANG_MING_STAGE", name_en: "Yang Ming Stage (Bright Yang)", diagnostic_tip: "Demam tinggi, haus besar, nadi besar.", primary_organs: [], wuxing_element: "Mixed", treatment_principle: ["Clear Heat in Yang Ming"], acupuncture_points: ["ST44","LI11","ST25","GV14"], herbal_prescription: "Bai Hu Tang or Da Cheng Qi Tang" },
  { id: "SHAO_YANG_STAGE", name_en: "Shao Yang Stage (Lesser Yang)", diagnostic_tip: "Bolak-balik panas dingin, rasa pahit.", primary_organs: [], wuxing_element: "Mixed", treatment_principle: ["Harmonize Shao Yang"], acupuncture_points: ["TE5","GB41","GB34"], herbal_prescription: "Xiao Chai Hu Tang" },
  { id: "TAI_YIN_STAGE", name_en: "Tai Yin Stage (Greater Yin)", diagnostic_tip: "Perut penuh, diare, mual.", primary_organs: [], wuxing_element: "Mixed", treatment_principle: ["Warm Spleen","Disperse Cold"], acupuncture_points: ["SP3","ST36","CV12","BL20"], herbal_prescription: "Li Zhong Wan" },
  { id: "SHAO_YIN_STAGE", name_en: "Shao Yin Stage (Lesser Yin)", diagnostic_tip: "Dingin ekstrim atau panas ekstrim dari defisiensi.", primary_organs: [], wuxing_element: "Mixed", treatment_principle: ["Warm Kidney Yang","Nourish Kidney Yin"], acupuncture_points: ["KD3","KD7","CV4","GV4"], herbal_prescription: "Si Ni Tang or Huang Lian E Jiao Tang" },
  { id: "JUE_YIN_STAGE", name_en: "Jue Yin Stage (Terminal Yin)", diagnostic_tip: "Rasa haus, energi naik ke dada, parasit.", primary_organs: [], wuxing_element: "Mixed", treatment_principle: ["Harmonize Liver and Stomach","Clear Heat above","Warm Cold below"], acupuncture_points: ["LR3","PC6","CV12","ST36"], herbal_prescription: "Wu Mei Wan" },
  { id: "WEI_QI_YING_XUE_LEVELS", name_en: "Wei, Qi, Ying, Xue Levels", diagnostic_tip: "Empat tingkatan penyakit panas/demam parah.", primary_organs: [], wuxing_element: "Mixed", treatment_principle: ["Clear Heat at corresponding level"], acupuncture_points: ["LI11","GV14","PC3","BL40"], herbal_prescription: "Yin Qiao San, Bai Hu Tang, Qing Ying Tang, Xi Jiao Di Huang Tang" },
  { id: "UPPER_MIDDLE_LOWER_BURNER_PATTERNS", name_en: "Upper, Middle, Lower Burner Patterns", diagnostic_tip: "Sindrom berdasarkan lokasi tiga pemanas", primary_organs: [], wuxing_element: "Mixed", treatment_principle: ["Treat according to burner affected"], acupuncture_points: ["CV17","CV12","CV6"], herbal_prescription: "San Jiao formulas" }
].map(p => ({
  ...p,
  name_id: p.name_en, // Placeholder
  pattern_type: "mixed", // Placeholder
  clinical_manifestations: p.diagnostic_tip ? toArray(p.diagnostic_tip) : [],
  tongue: [],
  pulse: [],
  key_symptoms: [],
  treatment_principle: p.treatment_principle || [],
  acupuncture_points: p.acupuncture_points || [],
  herbal_prescription: p.herbal_prescription || ""
}));
