import { Syndrome } from '../../types';

export const MACIOCIA_SYNDROMES: Syndrome[] = [
  {
    id: "heart-fire-blazing",
    name_id: "Api Jantung Berkobar",
    name_en: "Heart Fire-Blazing",
    name_pinyin: "Xin Huo Shang Yan",
    primary_organs: ["Heart"],
    wuxing_element: "Fire",
    pattern_type: "Excess Heat",
    clinical_manifestations: ["Palpitations", "Thirst", "Mouth and tongue ulcers", "Mental restlessness", "Feeling of heat, red face", "Insomnia", "Dark urine or blood in urine", "Bitter taste"],
    tongue: ["Red tongue, tip redder and swollen with red points, yellow coating, possible midline crack"],
    pulse: ["Full-Rapid-Overflowing (left Front position), may be Hasty"],
    key_symptoms: ["Tongue ulcers", "Thirst", "Palpitations", "Red tongue"],
    treatment_principle: ["Clear the Heart, drain Fire, and calm the Mind (Shen)"],
    acupuncture_points: ["HE-9 Shaochong", "HE-7 Shenmen", "SP-6 Sanyinjiao", "LI-11 Quchi", "Du-24 Shenting", "Du-19 Houding", "HE-8 Shaofu", "Ren-15 Jiuwei", "KI-6 Zhaohai"],
    herbal_prescription: "Xie Xin Tang",
    needling_method: "Reducing on all points except SP-6 and KI-6 (reinforcing); no moxa",
    diagnostic_tip: "Tongue ulcers + red tongue tip + palpitations = classic Heart Fire"
  },
  {
    id: "liver-fire-blazing",
    name_id: "Api Liver Berkobar",
    name_en: "Liver Fire-Blazing",
    name_pinyin: "Gan Huo Shang Yan",
    primary_organs: ["Liver"],
    wuxing_element: "Wood",
    pattern_type: "Excess Heat",
    clinical_manifestations: ["Headache, dizziness", "Red face and eyes", "Irritability, outbursts of anger", "Bitter taste, dry throat", "Constipation", "Dark-yellow urine", "Tinnitus"],
    tongue: ["Red tongue with redder sides and yellow coating"],
    pulse: ["Wiry and Rapid"],
    key_symptoms: ["Red eyes/face", "Anger, irritability", "Bitter taste", "Wiry-rapid pulse"],
    treatment_principle: ["Clear Liver-Fire, drain Heat, and subdue rising"],
    acupuncture_points: ["LIV-2 Xingjian", "LIV-3 Taichong", "GB-20 Fengchi", "LI-11 Quchi", "Du-24 Shenting", "Taiyang (EX-HN5)"],
    herbal_prescription: "Long Dan Xie Gan Tang",
    needling_method: "Reducing on all points; no moxa"
  },
  {
    id: "invasion-lungs-wind-cold",
    name_id: "Invasi Angin-Dingin ke Paru",
    name_en: "Invasion of the Lungs by Wind-Cold",
    primary_organs: ["Lungs"],
    wuxing_element: "Metal",
    pattern_type: "Cold Excess (Exterior)",
    clinical_manifestations: ["Aversion to cold, mild fever", "No sweating", "Body aches, stiff neck/occiput", "Cough with thin white sputum", "Runny/blocked nose"],
    tongue: ["Thin white coating"],
    pulse: ["Floating-Tight"],
    key_symptoms: ["No sweating", "Aversion to cold", "Thin white sputum"],
    treatment_principle: ["Release Exterior, expel Wind-Cold, restore Lung diffusion"],
    acupuncture_points: ["LU-7 Lieque", "LI-4 Hegu", "BL-12 Fengmen", "GB-20 Fengchi"],
    herbal_prescription: "Ma Huang Tang"
  },
  {
    id: "stagnation-cold-liver-channel",
    name_id: "Stagnasi Dingin di Meridian Hati",
    name_en: "Stagnation of Cold in the Liver Channel",
    primary_organs: ["Liver"],
    wuxing_element: "Wood",
    pattern_type: "Cold Excess (Interior)",
    clinical_manifestations: ["Severe lower abdominal pain radiating to genitals/testes", "Pain worse with cold, better with warmth", "Possible hernia, contraction of scrotum/vulva", "Cold sensation in lower abdomen"],
    tongue: ["Normal or pale, white coating"],
    pulse: ["Deep-Wiry-Slow/Tight"],
    key_symptoms: ["Severe lower abdominal/genital pain worse with cold"],
    treatment_principle: ["Warm Liver channel, expel Cold, move Qi and Blood"],
    acupuncture_points: ["LIV-3 Taichong", "LIV-8 Ququan", "ST-29 Guilai", "Ren-4 Guanyuan", "SP-6 Sanyinjiao"],
    herbal_prescription: "Tian Tai Wu Yao San"
  },
  {
    id: "cold-phlegm-lungs",
    name_id: "Dahak-Dingin di Paru",
    name_en: "Cold-Phlegm in the Lungs",
    primary_organs: ["Lungs"],
    wuxing_element: "Metal",
    pattern_type: "Cold Excess (Interior)",
    clinical_manifestations: ["Cough with copious white watery sputum", "Cough worse with cold", "Feeling cold, cold hands", "Phlegm in throat", "Oppression in chest", "Heaviness, dizziness"],
    tongue: ["Swollen and wet with sticky white coating"],
    pulse: ["Slippery-Slow"],
    key_symptoms: ["Copious white watery sputum", "Feeling cold"],
    treatment_principle: ["Resolve Dampness and Phlegm, restore descending of Lung-Qi"],
    acupuncture_points: ["LU-5 Chize", "LU-7 Lieque", "ST-40 Fenglong", "Ren-17 Shanzhong", "Ren-12 Zhongwan"],
    herbal_prescription: "Er Chen Tang"
  },
  {
    id: "cold-dampness-spleen",
    name_id: "Kelembapan-Dingin Menginvasi Limpa",
    name_en: "Cold-Dampness Invading the Spleen",
    primary_organs: ["Spleen"],
    wuxing_element: "Earth",
    pattern_type: "Cold Excess (Interior)",
    clinical_manifestations: ["Epigastric/abdominal fullness", "Poor appetite, nausea", "Loose stools/diarrhea", "Heavy body/limbs, tiredness", "Possible edema"],
    tongue: ["Pale with sticky white coating"],
    pulse: ["Slippery-Slow"],
    key_symptoms: ["Abdominal fullness + loose stools + heavy body"],
    treatment_principle: ["Warm Spleen Yang and resolve Dampness"],
    acupuncture_points: ["Ren-12 Zhongwan", "ST-36 Zusanli", "SP-3 Taibai", "SP-9 Yinlingquan", "BL-20 Pishu"],
    herbal_prescription: "Huo Xiang Zheng Qi San"
  },
  {
    id: "cold-invading-stomach",
    name_id: "Dingin Menginvasi Lambung",
    name_en: "Cold Invading the Stomach",
    primary_organs: ["Stomach"],
    wuxing_element: "Earth",
    pattern_type: "Cold Excess (Interior)",
    clinical_manifestations: ["Epigastric pain better with warmth", "Pain worse with cold foods", "Vomiting clear fluids, no thirst", "Preference for warm drinks"],
    tongue: ["Pale, white coating"],
    pulse: ["Deep-Slow-Tight"],
    key_symptoms: ["Epigastric pain relieved by warmth"],
    treatment_principle: ["Warm Stomach, expel Cold, descend Stomach Qi"],
    acupuncture_points: ["Ren-12 Zhongwan", "ST-36 Zusanli", "ST-21 Liangmen", "PC-6 Neiguan"],
    herbal_prescription: "Liang Fu Wan"
  },
  {
    id: "cold-invading-large-intestine",
    name_id: "Dingin Menginvasi Usus Besar",
    name_en: "Cold Invading the Large Intestine",
    primary_organs: ["Large Intestine"],
    wuxing_element: "Metal",
    pattern_type: "Cold Excess (Interior)",
    clinical_manifestations: ["Abdominal pain better with warmth", "Diarrhea with watery stools", "Borborygmi", "Cold feeling in abdomen"],
    tongue: ["Pale with white coating"],
    pulse: ["Deep-Slow"],
    key_symptoms: ["Abdominal pain + diarrhea better with warmth"],
    treatment_principle: ["Warm Intestines, expel Cold, stop diarrhea"],
    acupuncture_points: ["ST-25 Tianshu", "ST-37 Shangjuxu", "Ren-6 Qihai", "SP-9 Yinlingquan"],
    herbal_prescription: "Li Zhong Wan"
  },
  {
    id: "damp-cold-bladder",
    name_id: "Lembap-Dingin di Kandung Kemih",
    name_en: "Damp-Cold in the Bladder",
    primary_organs: ["Bladder"],
    wuxing_element: "Water",
    pattern_type: "Cold Excess (Lower Burner)",
    clinical_manifestations: ["Difficult urination, scanty urine", "Turbid/cloudy urine", "Lower abdominal heaviness", "Feeling cold in lower body"],
    tongue: ["Pale, thick sticky white coating"],
    pulse: ["Soggy-Slow"],
    key_symptoms: ["Difficult urination + turbid urine"],
    treatment_principle: ["Warm Bladder Yang, resolve Dampness, promote urination"],
    acupuncture_points: ["Ren-3 Zhongji", "BL-28 Pangguangshu", "BL-22 Sanjiaoshu", "SP-9 Yinlingquan", "ST-28 Shuidao"],
    herbal_prescription: "Wu Ling San / Wei Ling Tang"
  },
  {
    id: "heart-yang-deficiency",
    name_id: "Defisiensi Yang Jantung",
    name_en: "Heart-Yang Deficiency",
    primary_organs: ["Heart"],
    wuxing_element: "Fire",
    pattern_type: "Cold Deficiency",
    clinical_manifestations: ["Palpitations", "Shortness of breath on exertion", "Tiredness, spontaneous sweating", "Feeling cold, cold hands"],
    tongue: ["Pale, slightly wet"],
    pulse: ["Deep-Weak (may be Knotted)"],
    key_symptoms: ["Palpitations + cold hands + spontaneous sweating"],
    treatment_principle: ["Tonify and warm Heart-Yang"],
    acupuncture_points: ["HE-5 Tongli", "P-6 Neiguan", "BL-15 Xinshu", "Ren-17 Shanzhong", "Ren-6 Qihai"],
    herbal_prescription: "Rou Fu Bao Yuan Tang"
  },
  {
    id: "spleen-yang-deficiency",
    name_id: "Defisiensi Yang Limpa",
    name_en: "Spleen-Yang Deficiency",
    primary_organs: ["Spleen"],
    wuxing_element: "Earth",
    pattern_type: "Cold Deficiency",
    clinical_manifestations: ["Poor appetite, abdominal distension", "Loose stools, undigested food", "Cold feeling in abdomen", "Tiredness, heaviness"],
    tongue: ["Pale, swollen, teeth marks, white moist coating"],
    pulse: ["Deep-Weak/Slow"],
    key_symptoms: ["Loose stools + cold abdomen + tiredness"],
    treatment_principle: ["Warm and tonify Spleen-Yang"],
    acupuncture_points: ["Ren-12 Zhongwan", "ST-36 Zusanli", "SP-3 Taibai", "SP-6 Sanyinjiao", "BL-20 Pishu", "Du-4 Mingmen"],
    herbal_prescription: "Li Zhong Wan / Fu Zi Li Zhong Wan"
  },
  {
    id: "kidney-yang-deficiency",
    name_id: "Defisiensi Yang Ginjal",
    name_en: "Kidney-Yang Deficiency",
    primary_organs: ["Kidney"],
    wuxing_element: "Water",
    pattern_type: "Cold Deficiency",
    clinical_manifestations: ["Feeling cold, cold back and knees", "Soreness/weakness lower back", "Fatigue", "Scanty-clear urination or edema", "Low libido"],
    tongue: ["Pale, swollen, wet"],
    pulse: ["Deep-Weak-Slow"],
    key_symptoms: ["Cold back/knees + lower back weakness + low libido"],
    treatment_principle: ["Warm and tonify Kidney-Yang"],
    acupuncture_points: ["Du-4 Mingmen", "Ren-4 Guanyuan", "Ren-6 Qihai", "BL-23 Shenshu", "KI-3 Taixi", "KI-7 Fuliu"],
    herbal_prescription: "Jin Gui Shen Qi Wan / You Gui Wan"
  },
  {
    id: "heart-yin-deficiency",
    name_id: "Defisiensi Yin Jantung",
    name_en: "Heart-Yin Deficiency",
    primary_organs: ["Heart"],
    wuxing_element: "Fire",
    pattern_type: "Heat Deficiency (Empty-Heat)",
    clinical_manifestations: ["Palpitations", "Insomnia", "Dream-disturbed sleep", "Anxiety, mental restlessness", "Dry mouth and throat", "Night sweating"],
    tongue: ["Red or slightly red, without coating, deep midline crack to tip"],
    pulse: ["Floating-Empty and Rapid (or Fine-Rapid)"],
    key_symptoms: ["Insomnia with restlessness + night sweating + red tongue without coating"],
    treatment_principle: ["Nourish Heart-Yin, calm the Mind, clear Empty-Heat if pronounced"],
    acupuncture_points: ["HE-7 Shenmen", "Ren-14 Juque", "Ren-15 Jiuwei", "Ren-4 Guanyuan", "HE-6 Yinxi", "SP-6 Sanyinjiao", "KI-6 Zhaohai"],
    herbal_prescription: "Tian Wang Bu Xin Dan"
  },
  {
    id: "liver-yin-deficiency",
    name_id: "Defisiensi Yin Hati",
    name_en: "Liver-Yin Deficiency",
    primary_organs: ["Liver"],
    wuxing_element: "Wood",
    pattern_type: "Heat Deficiency (Empty-Heat)",
    clinical_manifestations: ["Dizziness", "Depression", "Dry eyes, blurred vision", "Dry hair and skin", "Scanty menstruation", "Muscle cramps"],
    tongue: ["Normal or slightly red, without coating"],
    pulse: ["Floating-Empty"],
    key_symptoms: ["Dry eyes + blurred vision + tongue without coating"],
    treatment_principle: ["Tonify Liver and nourish Yin, clear Empty-Heat if necessary"],
    acupuncture_points: ["LIV-8 Ququan", "SP-6 Sanyinjiao", "ST-36 Zusanli", "Ren-4 Guanyuan", "KI-3 Taixi"],
    herbal_prescription: "Yi Guan Jian"
  },
  {
    id: "lung-yin-deficiency",
    name_id: "Defisiensi Yin Paru",
    name_en: "Lung-Yin Deficiency",
    primary_organs: ["Lungs"],
    wuxing_element: "Metal",
    pattern_type: "Heat Deficiency (Empty-Heat)",
    clinical_manifestations: ["Dry cough or scanty sticky sputum", "Weak/hoarse voice", "Dry mouth and throat", "Night sweating", "Tiredness"],
    tongue: ["Normal-coloured or slightly red, dry, without coating in front"],
    pulse: ["Floating-Empty"],
    key_symptoms: ["Dry cough + hoarse voice + night sweating"],
    treatment_principle: ["Tonify Lung-Yin, nourish Body Fluids, clear Empty-Heat if necessary"],
    acupuncture_points: ["LU-9 Taiyuan", "Ren-17 Shanzhong", "BL-43 Gaohuangshu", "BL-13 Feishu"],
    herbal_prescription: "Bai He Gu Jin Tang"
  }
];

export default MACIOCIA_SYNDROMES;
