
import React, { useState, useRef } from 'react';
import { TcmDiagnosisResult } from '../types';
import { db } from '../services/db';
import { 
  BrainCircuit, FileText, FileDown, ShieldCheck, MapPin, 
  Heart, Leaf, Save, Check, Loader2, Anchor, Zap, Activity, Sparkles, Scale, Copy, Share2, Info, ChevronDown, ChevronUp, Printer, QrCode
} from 'lucide-react';
import DoctorNoteModal from './DoctorNoteModal';
import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';

interface Props {
  diagnosis?: TcmDiagnosisResult | null;
  isPregnant: boolean;
  onShowVisualizer: (element?: string) => void;
  patientContext?: any;
}

const DiagnosisCard: React.FC<Props> = ({ diagnosis, isPregnant, onShowVisualizer, patientContext }) => {
  const [showNoteModal, setShowNoteModal] = useState(false);
  const [isSaved, setIsSaved] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const [showFullBianZheng, setShowFullBianZheng] = useState(false);
  const cardRef = useRef<HTMLDivElement>(null);

  if (!diagnosis) return null;

  // Data untuk QR Code
  const qrData = encodeURIComponent(
    `TCM Diagnosis: ${diagnosis.patternId}\n` +
    `Prinsip Terapi: ${diagnosis.treatment_principle?.join(', ') || '-'}\n` +
    `Titik Akupunktur: ${diagnosis.recommendedPoints?.map(p => p.code).join(', ') || '-'}\n` +
    `Generated by TCM WuXing Pro`
  );

  const qrUrl = `https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=${qrData}`;

  const handlePrint = () => window.print();

  const handleSave = () => {
    try {
      db.patients.add({
        id: Date.now().toString(),
        patientName: patientContext?.patientName || "Pasien Anonim",
        age: patientContext?.age || "-",
        sex: patientContext?.sex || "-",
        phone: patientContext?.phone || "",
        email: patientContext?.email || "",
        address: patientContext?.address || "",
        complaint: patientContext?.complaint || "Konsultasi Chat",
        symptoms: patientContext?.symptoms || "",
        selectedSymptoms: patientContext?.selectedSymptoms || [],
        tongue: patientContext?.tongue || { body_color: 'Normal', coating_color: 'Normal' },
        pulse: patientContext?.pulse || { qualities: [] },
        diagnosis: diagnosis,
        timestamp: Date.now(),
        medicalHistory: patientContext?.medicalHistory || "",
        biomedicalDiagnosis: patientContext?.biomedicalDiagnosis || "",
        icd10: patientContext?.icd10 || "",
        notes: patientContext?.notes || ""
      });
      setIsSaved(true);
      setTimeout(() => setIsSaved(false), 3000);
    } catch (err) {
      console.error("Gagal menyimpan ke arsip:", err);
      alert("Gagal menyimpan data ke database lokal.");
    }
  };

  const handleExportPDF = async () => {
    if (!cardRef.current || isExporting) return;
    setIsExporting(true);
    try {
      const canvas = await html2canvas(cardRef.current, { 
        scale: 2, 
        useCORS: true, 
        backgroundColor: '#020617',
        logging: false
      });
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      const imgProps = pdf.getImageProperties(imgData);
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;
      pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
      pdf.save(`TCM_Resep_${diagnosis.patternId.replace(/\s+/g, '_')}.pdf`);
    } catch (e) { 
      alert("Ekspor Gagal. Pastikan browser mendukung Canvas."); 
    } finally { 
      setIsExporting(false); 
    }
  };

  const ScoreBadge = ({ score }: { score?: number }) => {
    if (score === undefined) return null;
    const colorClass = score >= 80 
      ? 'bg-emerald-100 text-emerald-700 border-emerald-200' 
      : score >= 50 
        ? 'bg-amber-100 text-amber-700 border-amber-200' 
        : 'bg-purple-100 text-purple-500 border-purple-200';
    
    return (
      <span className={`text-[9px] font-black px-1.5 py-0.5 rounded border whitespace-nowrap uppercase tracking-tighter ${colorClass}`}>
        {score}% Match
      </span>
    );
  };

  const handleCopy = () => {
    const text = `
TCM DIAGNOSIS REPORT
--------------------
Pattern: ${diagnosis.patternId}
Explanation: ${diagnosis.explanation}

TREATMENT PRINCIPLE:
${diagnosis.treatment_principle?.join(', ') || 'N/A'}

PRESCRIPTION:
${diagnosis.classical_prescription || 'N/A'}

ACUPUNCTURE POINTS:
${diagnosis.recommendedPoints?.map(p => `${p.code}: ${p.description}`).join('\n') || 'N/A'}

MASTER TUNG POINTS:
${diagnosis.masterTungPoints?.map(p => `${p.code}: ${p.description}`).join('\n') || 'N/A'}

LIFESTYLE ADVICE:
${diagnosis.lifestyleAdvice}
    `.trim();
    navigator.clipboard.writeText(text);
    alert("Diagnosis copied to clipboard!");
  };

  const handleShare = async () => {
    const text = `TCM Diagnosis: ${diagnosis.patternId}\nPrinciple: ${diagnosis.treatment_principle?.join(', ')}\nPrescription: ${diagnosis.classical_prescription}`;
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'TCM Diagnosis Report',
          text: text,
          url: window.location.href
        });
      } catch (err) {
        console.error("Share failed:", err);
      }
    } else {
      handleCopy();
    }
  };

  return (
    <div className="mt-6 animate-fade-in print:bg-white print:shadow-none">
      <DoctorNoteModal 
        isOpen={showNoteModal} 
        onClose={() => setShowNoteModal(false)} 
        diagnosis={diagnosis}
        initialPatientData={{ name: patientContext?.patientName, age: patientContext?.age }}
      />

      <div ref={cardRef} className="bg-white border border-purple-100 rounded-3xl p-8 shadow-2xl relative overflow-hidden print:bg-white print:border-none print:p-0">
        {/* HEADER */}
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6 mb-8 print:mb-6">
           <div className="flex items-center gap-4">
              <div className="w-14 h-14 bg-purple-50 border border-purple-200 rounded-2xl flex items-center justify-center shadow-inner">
                 <BrainCircuit className="text-tcm-primary w-8 h-8" />
              </div>
              <div>
                 <h2 className="text-3xl font-black text-purple-950 tracking-tighter print:text-2xl">
                    {diagnosis.patternId}
                 </h2>
                 <p className="text-purple-500 text-sm font-medium print:text-xs">Bian Zheng • Maciocia</p>
              </div>
           </div>
           <div className="flex gap-3 print:hidden">
              <button 
                onClick={handleSave} 
                title="Simpan ke Arsip Pasien"
                className={`px-5 py-2.5 rounded-2xl border transition-all flex items-center gap-2 group text-sm font-bold ${
                  isSaved 
                  ? 'text-white border-emerald-500 bg-emerald-500 shadow-lg shadow-emerald-900/20' 
                  : 'text-emerald-700 border-emerald-200 hover:bg-emerald-200 bg-emerald-100'
                }`}
              >
                {isSaved ? <><Check className="w-4 h-4" /><span>Tersimpan</span></> : <><Save className="w-4 h-4 group-hover:scale-110" /><span>Arsipkan</span></>}
              </button>
              <button onClick={() => setShowNoteModal(true)} className="px-5 py-2.5 bg-fuchsia-600 hover:bg-fuchsia-700 text-white rounded-2xl text-sm font-bold flex items-center gap-2 shadow-lg shadow-fuchsia-900/20 transition-all active:scale-95">
                <FileText className="w-4 h-4" /> Rx Note
              </button>
           </div>
        </div>

        {/* === ANALISA WU XING LENGKAP (BARU & DETAIL) === */}
        <div className="mb-8 bg-gradient-to-br from-purple-50 to-amber-50 border border-purple-200 rounded-3xl p-7">
          <div className="flex items-center gap-3 mb-5">
            <Zap className="w-6 h-6 text-amber-600" />
            <h4 className="font-black text-amber-700 text-lg">Analisa Wu Xing Pathological Process</h4>
          </div>

          <div className="space-y-6 text-sm leading-relaxed text-purple-800">
            
            {/* Elemen Utama */}
            <div>
              <span className="font-semibold text-purple-600">Elemen yang Terganggu Utama:</span>
              <span className="ml-2 font-medium">{diagnosis.wuxingElement || 'Belum terdeteksi'}</span>
            </div>

            {/* Penjelasan Detail */}
            {diagnosis.wuxingRelationships && diagnosis.wuxingRelationships.length > 0 ? (
              diagnosis.wuxingRelationships.map((rel: any, index: number) => (
                <div key={index} className="border-l-4 border-amber-500 pl-4 py-1">
                  <div className="flex items-center gap-2">
                    <span className="font-bold text-amber-600">
                      {rel.type === 'Cheng' || rel.type === 'Overacting' ? 'Cheng (Tertindas / Overacting)' : 
                       rel.type === 'Wu' || rel.type === 'Insulting' ? 'Wu (Merampok / Insulting)' : rel.type}
                    </span>
                  </div>
                  <p className="mt-1 text-purple-700">{rel.description}</p>
                  <p className="text-xs text-purple-500 mt-2">
                    {rel.type === 'Cheng' || rel.type === 'Overacting' 
                      ? 'Elemen yang terlalu kuat menekan elemen yang seharusnya dikendalikannya.' 
                      : 'Elemen yang seharusnya dikendalikan justru menyerang balik elemen pengendalinya.'}
                  </p>
                </div>
              ))
            ) : (
              <p className="italic text-purple-500">
                Saat ini tidak terdeteksi hubungan patologis Wu Xing yang signifikan. 
                Pola ini masih dalam kondisi relatif seimbang atau perlu data tambahan.
              </p>
            )}

            <div className="text-xs text-purple-400 border-t border-purple-100 pt-4">
              Teori Wu Xing: Sheng (melahirkan/menutrisi) dan Ke (mengendalikan) adalah siklus normal. 
              Ketika terjadi Cheng (overacting) atau Wu (insulting), maka muncul ketidakseimbangan patologis.
            </div>
          </div>
        </div>


        {/* QR CODE SECTION */}
        <div className="flex justify-end mb-6 print:hidden">
          <div className="flex flex-col items-center bg-white border border-purple-200 rounded-3xl p-4 shadow-sm">
            <div className="flex items-center gap-2 text-purple-600 text-xs font-bold mb-2">
              <QrCode className="w-4 h-4" />
              QR Diagnosis
            </div>
            <img 
              src={qrUrl} 
              alt="QR Code Diagnosis" 
              className="w-40 h-40 border border-purple-100 rounded-2xl"
            />
            <p className="text-[10px] text-purple-400 mt-2 text-center">Scan untuk info lengkap diagnosis</p>
          </div>
        </div>

        {/* PATHOGENESIS */}
        <div className="bg-purple-50 border border-purple-100 rounded-2xl p-5 mb-6">
          <div className="flex items-center gap-2 mb-3 text-purple-600">
            <Info className="w-5 h-5" />
            <span className="font-black uppercase text-xs tracking-widest">Patogenesis (Bian Zheng)</span>
          </div>
          <p className="text-purple-800 leading-relaxed text-sm">
            {diagnosis.explanation || "Ketidakseimbangan Yin-Yang, Qi, Blood, atau organ sesuai pola Maciocia."}
          </p>
        </div>

        {/* TOMBOL EXPAND ALL & CETAK */}
        <div className="flex items-center justify-between mb-6 print:hidden">
          <button
            onClick={() => setShowFullBianZheng(!showFullBianZheng)}
            className="flex items-center gap-2 px-5 py-3 bg-white border border-purple-200 hover:border-purple-300 rounded-2xl font-bold text-purple-700 text-sm transition-all"
          >
            {showFullBianZheng ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
            {showFullBianZheng ? 'Collapse All' : 'Expand All'}
          </button>

          <button
            onClick={handlePrint}
            className="flex items-center gap-2 px-6 py-3 bg-purple-600 text-white rounded-2xl font-bold text-sm hover:bg-purple-700 transition-all"
          >
            <Printer className="w-4 h-4" />
            Print
          </button>
        </div>

        {/* DETAIL BIAN ZHENG LENGKAP */}
        <div className={`${showFullBianZheng ? 'block' : 'hidden print:block'} space-y-8 border border-purple-100 rounded-3xl p-6 bg-purple-50/70 mb-8 print:bg-white print:border-none print:p-0 print:mb-6`}>

        {/* KEY SYMPTOMS + TONGUE & PULSE */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
          {/* Key Symptoms */}
          <div className="bg-amber-50 border border-amber-200 rounded-2xl p-5">
            <h4 className="font-black text-amber-700 uppercase text-xs mb-3">Gejala Kunci</h4>
            <ul className="space-y-2 text-sm">
              {diagnosis.keySymptoms && diagnosis.keySymptoms.length > 0 ? (
                diagnosis.keySymptoms.map((sym, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="text-amber-500">•</span>
                    <span className="text-amber-900">{sym}</span>
                  </li>
                ))
              ) : (
                <li className="flex items-start gap-2">
                  <span className="text-amber-500">•</span>
                  <span className="text-amber-900 italic">Tidak ada gejala kunci spesifik yang dicatat.</span>
                </li>
              )}
            </ul>
          </div>

          {/* Tongue & Pulse */}
          <div className="bg-emerald-50 border border-emerald-200 rounded-2xl p-5">
            <h4 className="font-black text-emerald-700 uppercase text-xs mb-3">Lidah & Nadi</h4>
            <div className="text-sm space-y-3">
              <div>
                <span className="font-bold text-emerald-600">Lidah:</span> 
                <span className="ml-2 text-emerald-800">{diagnosis.tongueDescription || "Normal"}</span>
              </div>
              <div>
                <span className="font-bold text-emerald-600">Nadi:</span> 
                <span className="ml-2 text-emerald-800">{diagnosis.pulseDescription || "Normal"}</span>
              </div>
            </div>
          </div>
        </div>

        {/* TREATMENT PRINCIPLE */}
        {(diagnosis.treatment_principle && diagnosis.treatment_principle.length > 0) && (
           <div className="mb-8">
              <h4 className="text-xs font-black tracking-widest text-purple-500 mb-3">PRINSIP TERAPI (Bian Zheng)</h4>
              <div className="bg-purple-600 text-white p-5 rounded-2xl">
                {diagnosis.treatment_principle.map((principle, i) => (
                  <div key={i} className="flex items-center gap-3 mb-2 last:mb-0">
                    <span className="text-2xl text-purple-300">→</span>
                    <span className="font-medium">{principle}</span>
                  </div>
                ))}
              </div>
           </div>
        )}

        {/* TABEL BEN & BIAO */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-8">
           {/* BEN (ROOT) TABLE */}
           <div className="bg-purple-50/50 rounded-2xl border border-purple-200 overflow-hidden shadow-sm">
              <div className="bg-purple-100 px-4 py-2 border-b border-purple-200 flex items-center gap-2">
                 <Anchor className="w-4 h-4 text-purple-600" />
                 <span className="text-[10px] font-black text-purple-600 uppercase tracking-[0.2em]">BEN (Root / Akar)</span>
              </div>
              <div className="p-0">
                 <table className="w-full text-xs text-left">
                    <tbody className="divide-y divide-purple-100">
                       {diagnosis.differentiation?.ben?.map((item, i) => (
                          <tr key={i} className="hover:bg-white transition-colors">
                             <td className="px-4 py-3 font-bold text-purple-500 uppercase tracking-tighter w-1/3 border-r border-purple-100 bg-purple-50/30">{item.label}</td>
                             <td className="px-4 py-3">
                                <div className="flex justify-between items-center gap-2">
                                   <span className="text-purple-900 italic">{item.value}</span>
                                   <ScoreBadge score={item.score} />
                                </div>
                             </td>
                          </tr>
                       )) || (
                         <tr><td className="px-4 py-3 text-purple-400 italic">Menganalisis akar masalah...</td></tr>
                       )}
                    </tbody>
                 </table>
              </div>
           </div>

           {/* BIAO (BRANCH) TABLE */}
           <div className="bg-amber-50/50 rounded-2xl border border-amber-200 overflow-hidden shadow-sm">
              <div className="bg-amber-100 px-4 py-2 border-b border-amber-200 flex items-center gap-2">
                 <Zap className="w-4 h-4 text-amber-600" />
                 <span className="text-[10px] font-black text-amber-600 uppercase tracking-[0.2em]">BIAO (Branch / Cabang)</span>
              </div>
              <div className="p-0">
                 <table className="w-full text-xs text-left">
                    <tbody className="divide-y divide-amber-100">
                       {diagnosis.differentiation?.biao?.map((item, i) => (
                          <tr key={i} className="hover:bg-white transition-colors">
                             <td className="px-4 py-3 font-bold text-amber-600 uppercase tracking-tighter w-1/3 border-r border-amber-100 bg-amber-50/30">{item.label}</td>
                             <td className="px-4 py-3">
                                <div className="flex justify-between items-center gap-2">
                                   <span className="text-amber-900 italic">{item.value}</span>
                                   <ScoreBadge score={item.score} />
                                </div>
                             </td>
                          </tr>
                       )) || (
                         <tr><td className="px-4 py-3 text-amber-500 italic">Menganalisis manifestasi cabang...</td></tr>
                       )}
                    </tbody>
                 </table>
              </div>
           </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 mb-8">
           <div className="lg:col-span-12">
              <div className="mb-8">
                 <h4 className="text-xs font-black tracking-widest text-purple-500 mb-4">RESEP AKUPUNKTUR</h4>
                 <div className="grid grid-cols-2 sm:grid-cols-3 gap-4">
                    {diagnosis.recommendedPoints?.map((pt, i) => (
                       <div key={i} className="bg-white border border-purple-200 p-4 rounded-2xl hover:border-purple-400 transition-all shadow-sm">
                          <div className="font-bold text-purple-700">{pt.code}</div>
                          <div className="text-xs text-purple-500 mt-1">{pt.description}</div>
                       </div>
                    ))}
                 </div>
              </div>
           </div>
        </div>

        {/* MASTER TUNG POINTS */}
        {diagnosis.masterTungPoints && diagnosis.masterTungPoints.length > 0 && (
           <div className="mb-8">
              <div className="flex items-center gap-3 mb-4">
                 <Sparkles className="w-5 h-5 text-amber-500" />
                 <h4 className="text-[10px] font-black text-amber-600 uppercase tracking-[0.3em]">Titik Master Tung ({diagnosis.masterTungPoints.length} Titik)</h4>
              </div>
              <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3">
                 {diagnosis.masterTungPoints.map((pt, i) => (
                    <div key={i} className="bg-amber-50/50 border border-amber-200 p-4 rounded-2xl hover:border-amber-400 hover:bg-white transition-all group shadow-inner">
                       <div className="flex items-center justify-between mb-2">
                          <span className="font-black text-amber-600 text-sm tracking-tighter group-hover:scale-110 transition-transform">{pt.code}</span>
                          <Activity className="w-3 h-3 text-amber-300" />
                       </div>
                       <p className="text-[10px] text-amber-700 leading-tight font-medium group-hover:text-amber-900 transition-colors">{pt.description}</p>
                    </div>
                 ))}
              </div>
           </div>
        )}

        {/* OBESITY & BEAUTY ACUPUNCTURE */}
        {(diagnosis.obesity_indication || diagnosis.beauty_acupuncture) && (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-8">
            {diagnosis.obesity_indication && (
              <div className="bg-teal-50/50 border border-teal-200 p-5 rounded-2xl flex items-start gap-4 shadow-sm">
                <div className="w-10 h-10 bg-teal-100 rounded-xl flex items-center justify-center border border-teal-200 shrink-0">
                  <Scale className="text-teal-600 w-5 h-5" />
                </div>
                <div>
                  <span className="text-[9px] font-black text-teal-600 uppercase tracking-widest block mb-1">Indikasi Obesitas</span>
                  <p className="text-[11px] text-teal-900 italic leading-snug">{diagnosis.obesity_indication}</p>
                </div>
              </div>
            )}
            {diagnosis.beauty_acupuncture && (
              <div className="bg-pink-50/50 border border-pink-200 p-5 rounded-2xl flex items-start gap-4 shadow-sm">
                <div className="w-10 h-10 bg-pink-100 rounded-xl flex items-center justify-center border border-pink-200 shrink-0">
                  <Sparkles className="text-pink-600 w-5 h-5" />
                </div>
                <div>
                  <span className="text-[9px] font-black text-pink-600 uppercase tracking-widest block mb-1">Akupuntur Kecantikan</span>
                  <p className="text-[11px] text-pink-900 italic leading-snug">{diagnosis.beauty_acupuncture}</p>
                </div>
              </div>
            )}
          </div>
        )}

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
           {(diagnosis.herbal_recommendation || diagnosis.classical_prescription) && (
              <div className="bg-emerald-50 border border-emerald-200 p-5 rounded-2xl flex items-center gap-5 shadow-sm">
                 <Leaf className="w-10 h-10 text-emerald-600 shrink-0" />
                 <div>
                    <div className="text-xs font-black text-emerald-600 mb-1">FORMULA HERBAL</div>
                    <div className="font-bold text-emerald-900 text-lg leading-tight">
                       {diagnosis.classical_prescription || diagnosis.herbal_recommendation?.formula_name || 'Individual'}
                    </div>
                 </div>
              </div>
           )}
           <div className="bg-rose-50 border border-rose-200 p-5 rounded-2xl flex items-center gap-4 shadow-sm">
              <div className="w-12 h-12 bg-rose-100 rounded-xl flex items-center justify-center border border-rose-200 shrink-0">
                 <Heart className="text-rose-600 w-6 h-6" />
              </div>
              <div>
                 <span className="text-[9px] font-black text-rose-600 uppercase tracking-widest block mb-1">Edukasi Gaya Hidup</span>
                 <p className="text-[11px] text-rose-900 italic leading-snug">{diagnosis.lifestyleAdvice}</p>
              </div>
           </div>
        </div>
        </div>

        {/* Tombol Export & Share */}
        <div className="flex justify-end gap-3 print:hidden mt-6">
          <button onClick={handlePrint} className="px-6 py-3 bg-purple-600 text-white rounded-2xl flex items-center gap-2 text-sm font-bold shadow-md hover:bg-purple-700 transition-colors">
            <Printer className="w-4 h-4" /> Print
          </button>
          <button onClick={handleCopy} className="px-6 py-3 text-purple-600 border border-purple-200 rounded-2xl hover:bg-purple-50 flex items-center gap-2 text-sm font-bold shadow-sm transition-colors">
            <Copy className="w-4 h-4" /> Copy
          </button>
          <button onClick={handleExportPDF} className="px-6 py-3 border border-purple-200 text-purple-700 bg-white rounded-2xl shadow-sm hover:bg-purple-50 flex items-center gap-2 text-sm font-bold transition-colors">
            {isExporting ? <Loader2 className="w-4 h-4 animate-spin" /> : <FileDown className="w-4 h-4" />} PDF
          </button>
        </div>

        <div className="text-center text-[10px] text-purple-400 mt-10 print:hidden">
          Diagnosis ini dihasilkan berdasarkan metode Bian Zheng Maciocia
        </div>
      </div>
    </div>
  );
};

export default DiagnosisCard;
