
import React, { useState, useRef, useMemo } from 'react';
import { X, Download, Upload, FileSignature, Printer, Calendar, User, MapPin, Clipboard, FileText, FileDown, Loader2 } from 'lucide-react';
import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';
import { TcmDiagnosisResult } from '../types';

interface Props {
  isOpen: boolean;
  onClose: () => void;
  diagnosis: TcmDiagnosisResult;
  initialPatientData?: {
    name?: string;
    age?: string;
    address?: string;
  };
}

const DoctorNoteModal: React.FC<Props> = ({ isOpen, onClose, diagnosis, initialPatientData }) => {
  const [clinicName, setClinicName] = useState('Klinik Utama TCM WuXing');
  const [doctorName, setDoctorName] = useState('Pakar Akupunktur Berlisensi');
  const [patientName, setPatientName] = useState(initialPatientData?.name || '');
  const [age, setAge] = useState(initialPatientData?.age || '');
  const [address, setAddress] = useState(initialPatientData?.address || '');
  const [date, setDate] = useState(new Date().toISOString().split('T')[0]);
  const [signature, setSignature] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  
  // === QR CODE GENERATION ===
  const qrData = useMemo(() => {
    return encodeURIComponent(
      `TCM Diagnosis: ${diagnosis.patternId}\n` +
      `Prinsip: ${diagnosis.treatment_principle?.join(', ') || '-'}\n` +
      `Titik: ${diagnosis.recommendedPoints?.map(p => p.code).join(', ') || '-'}\n` +
      `Generated by TCM WuXing Pro`
    );
  }, [diagnosis]);

  const qrUrl = `https://api.qrserver.com/v1/create-qr-code/?size=180x180&data=${qrData}`;

  const pointCodes = (diagnosis.recommendedPoints || []).map(p => p.code).join(', ');
  const detailedPoints = (diagnosis.recommendedPoints || []).map(p => `- ${p.code}: ${p.description}`).join('\n');

  const defaultNotes = `DIAGNOSIS TCM: ${diagnosis.patternId.toUpperCase()}

PRINSIP TERAPI:
${diagnosis.treatment_principle?.join(', ') || '-'}

DAFTAR TITIK AKUPUNKTUR:
${detailedPoints || '-'}

FORMULA HERBAL:
${diagnosis.classical_prescription || diagnosis.herbal_recommendation?.formula_name || 'Individual'}
${diagnosis.herbal_recommendation?.chief ? `Bahan Utama: ${diagnosis.herbal_recommendation.chief.join(', ')}` : ''}

SARAN & INSTRUKSI:
${diagnosis.lifestyleAdvice}`;

  const [notes, setNotes] = useState(defaultNotes);
  const receiptRef = useRef<HTMLDivElement>(null);

  const handleSignatureUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => setSignature(reader.result as string);
      reader.readAsDataURL(file);
    }
  };

  const generatePDF = async () => {
    if (!receiptRef.current) return;
    setIsGenerating(true);
    try {
      const canvas = await html2canvas(receiptRef.current, { scale: 3, useCORS: true, backgroundColor: '#ffffff' });
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a5');
      pdf.addImage(imgData, 'PNG', 0, 0, 148, 210);
      pdf.save(`Resep_TCM_${patientName || 'Pasien'}.pdf`);
    } catch (err) { alert("Gagal PDF"); } finally { setIsGenerating(false); }
  };

  const generateTextFile = () => {
    const content = `
RESEP KLINIS TCM WUXING
======================
Klinik: ${clinicName}
Dokter: ${doctorName}
Tanggal: ${date}

DATA PASIEN
-----------
Nama: ${patientName || '-'}
Umur: ${age}
Alamat: ${address || '-'}

CATATAN RESEP
-------------
${notes}

Dihasilkan secara otomatis oleh TCM WuXing Pro CDSS.
    `.trim();
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Resep_${patientName || 'Pasien'}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-purple-950/70 backdrop-blur-md p-4 animate-fade-in">
      <div className="bg-white border border-purple-100 w-full max-w-6xl h-[95vh] rounded-[2.5rem] shadow-2xl flex flex-col md:flex-row overflow-hidden border-tcm-primary/20">
        
        {/* Editor */}
        <div className="w-full md:w-[400px] bg-purple-50 p-8 overflow-y-auto border-r border-purple-100 flex flex-col gap-6 scrollbar-hide shadow-inner">
           <div className="flex items-center justify-between">
              <h2 className="text-xl font-black text-purple-950 flex items-center gap-3 tracking-tighter uppercase">
                 <FileSignature className="w-6 h-6 text-tcm-primary" /> Rx Generator
              </h2>
              <button onClick={onClose} className="text-purple-400 hover:text-purple-600 transition-colors p-1"><X className="w-7 h-7"/></button>
           </div>

           <div className="space-y-5">
              <div className="space-y-2">
                 <label className="text-[10px] font-black text-purple-500 uppercase tracking-widest ml-1">Klinik & Praktisi</label>
                 <input className="w-full bg-white border border-purple-200 rounded-2xl px-5 py-3 text-sm text-purple-900 focus:border-tcm-primary outline-none transition-all shadow-sm" value={clinicName} onChange={e => setClinicName(e.target.value)} placeholder="Nama Klinik" />
                 <input className="w-full bg-white border border-purple-200 rounded-2xl px-5 py-3 text-sm text-purple-900 focus:border-tcm-primary outline-none transition-all shadow-sm" value={doctorName} onChange={e => setDoctorName(e.target.value)} placeholder="Nama Dokter" />
              </div>

              <div className="space-y-2">
                 <label className="text-[10px] font-black text-purple-500 uppercase tracking-widest ml-1">Detail Pasien</label>
                 <div className="flex gap-2">
                    <input className="flex-1 bg-white border border-purple-200 rounded-2xl px-5 py-3 text-sm text-purple-900 focus:border-tcm-primary outline-none shadow-sm" value={patientName} onChange={e => setPatientName(e.target.value)} placeholder="Nama Pasien" />
                    <input className="w-20 bg-white border border-purple-200 rounded-2xl px-5 py-3 text-sm text-purple-900 focus:border-tcm-primary outline-none shadow-sm" value={age} onChange={e => setAge(e.target.value)} placeholder="Age" />
                 </div>
                 <input className="w-full bg-white border border-purple-200 rounded-2xl px-5 py-3 text-sm text-purple-900 focus:border-tcm-primary outline-none shadow-sm" value={address} onChange={e => setAddress(e.target.value)} placeholder="Alamat" />
              </div>

              <div className="space-y-2">
                 <label className="text-[10px] font-black text-purple-500 uppercase tracking-widest ml-1">Resep / Instruksi Klinis</label>
                 <textarea className="w-full h-56 bg-white border border-purple-200 rounded-2xl px-5 py-4 text-xs text-purple-900 font-mono leading-relaxed focus:border-tcm-primary outline-none resize-none scrollbar-hide shadow-sm" value={notes} onChange={e => setNotes(e.target.value)} />
              </div>

              <div className="grid grid-cols-2 gap-3">
                  <button onClick={generatePDF} disabled={isGenerating} className="py-4 bg-tcm-primary hover:brightness-110 text-white font-black rounded-2xl shadow-lg shadow-purple-900/20 flex items-center justify-center gap-2 text-xs uppercase tracking-widest transition-all active:scale-95">
                    {isGenerating ? <Loader2 className="w-4 h-4 animate-spin" /> : <><FileDown className="w-4 h-4" /> Download PDF</>}
                  </button>
                  <button onClick={generateTextFile} className="py-4 bg-purple-100 hover:bg-purple-200 text-purple-700 font-black rounded-2xl shadow-sm flex items-center justify-center gap-2 text-xs uppercase tracking-widest transition-all active:scale-95">
                    <Download className="w-4 h-4" /> Download Txt
                  </button>
              </div>
           </div>
        </div>

        {/* Live Preview */}
        <div className="flex-1 bg-purple-100 p-6 md:p-12 flex items-center justify-center overflow-auto scrollbar-hide">
            <div 
               ref={receiptRef}
               className="bg-white text-purple-950 shadow-2xl relative flex flex-col transform"
               style={{ width: '148mm', height: '210mm', minWidth: '148mm', minHeight: '210mm', padding: '15mm', fontFamily: 'serif' }}
            >
               <div className="border-b-2 border-purple-950 pb-4 mb-6 text-center">
                  <h1 className="text-xl font-black uppercase tracking-widest mb-1">{clinicName}</h1>
                  <p className="text-xs font-bold text-purple-800">{doctorName}</p>
                  <p className="text-[8px] text-purple-500 mt-2 uppercase tracking-[0.2em] font-sans">Traditional Chinese Medicine Specialist</p>
               </div>

               <div className="flex justify-between text-[10px] mb-8 font-sans border-b border-purple-100 pb-3">
                  <div className="space-y-1">
                     <p><span className="font-bold text-purple-400 uppercase tracking-tighter mr-2">Pasien:</span> <span className="font-black">{patientName || '-'}</span></p>
                     <p><span className="font-bold text-purple-400 uppercase tracking-tighter mr-2">Alamat:</span> <span className="font-black">{address || '-'}</span></p>
                  </div>
                  <div className="text-right space-y-1">
                     <p><span className="font-bold text-purple-400 uppercase tracking-tighter mr-2">Tanggal:</span> <span className="font-black">{date}</span></p>
                     <p><span className="font-bold text-purple-400 uppercase tracking-tighter mr-2">ID:</span> <span className="font-black">#{Date.now().toString().slice(-6)}</span></p>
                  </div>
               </div>

               <div className="flex-1 font-mono text-[11px] whitespace-pre-wrap leading-relaxed text-purple-900">
                  <div className="text-3xl font-black font-serif italic text-purple-300 mb-2">R/</div>
                  <div className="pl-2">{notes}</div>
               </div>

               <div className="mt-8 flex flex-col items-end">
                  <p className="text-[9px] text-purple-500 mb-4 font-sans uppercase tracking-widest">
                    {clinicName.split(' ')[2] || 'Pusat'}, {date}
                  </p>

                  {/* QR CODE */}
                  <div className="flex flex-col items-center border border-purple-200 p-3 rounded-2xl bg-white mb-4">
                    <img src={qrUrl} alt="QR Diagnosis" className="w-28 h-28" />
                    <p className="text-[9px] text-purple-400 mt-1">Scan untuk detail diagnosis lengkap</p>
                  </div>

                  <p className="text-xs font-black border-t-2 border-purple-950 pt-2 min-w-[150px] text-center uppercase tracking-tighter">
                    {doctorName}
                  </p>
               </div>
            </div>
        </div>
      </div>
    </div>
  );
};

export default DoctorNoteModal;
